#!/bin/bash
# GENERATED by generate_completion.py — DO NOT EDIT.
# Regenerate with: make completion  (or python -m xpcsjax.runtime.shell.generate_completion)
# Bash/zsh completion for xpcsjax CLI commands.


_XPCSJAX_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/xpcsjax"
_XPCSJAX_CACHE_TTL=300  # 5 minutes

if ! type mapfile &>/dev/null; then
    # ponytail: bash < 4 (e.g. macOS's stock /bin/bash 3.2) has no `mapfile`
    # builtin. Every completion arm below uses `mapfile -t NAME < <(cmd)`, so
    # shim that exact form once here rather than rewriting every call site.
    mapfile() {
        local __mapfile_arr=$2
        eval "$__mapfile_arr=()"
        local __mapfile_line
        while IFS= read -r __mapfile_line; do
            eval "$__mapfile_arr+=(\"\$__mapfile_line\")"
        done
        unset __mapfile_line
    }
fi

_xpcsjax_ensure_cache() {
    [[ -d "$_XPCSJAX_CACHE_DIR" ]] || mkdir -p "$_XPCSJAX_CACHE_DIR"
}

if ! type _init_completion &>/dev/null; then
    _init_completion() {
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    }

    if ! type _filedir &>/dev/null; then
        _filedir() {
            if [[ "$1" == "-d" ]]; then
                mapfile -t COMPREPLY < <(compgen -d -- "${cur}")
            else
                mapfile -t COMPREPLY < <(compgen -f -- "${cur}")
            fi
        }
    fi
fi

_xpcsjax_get_config_files() {
    _xpcsjax_ensure_cache
    # Key the cache file by cwd so a completion cached for one project's
    # config files is never served for a different directory within the TTL.
    local cache_file="$_XPCSJAX_CACHE_DIR/config_files_${PWD//\//_}"
    local now
    now=$(date +%s)

    if [[ -f "$cache_file" ]]; then
        local cache_time
        cache_time=$(stat -c %Y "$cache_file" 2>/dev/null || stat -f %m "$cache_file" 2>/dev/null)
        if [[ $((now - cache_time)) -lt $_XPCSJAX_CACHE_TTL ]]; then
            cat "$cache_file"
            return
        fi
    fi

    {
        find . -maxdepth 2 \( -name "*.yaml" -o -name "*.yml" \) -type f 2>/dev/null
        [[ -d "config" ]] && find config \( -name "*.yaml" -o -name "*.yml" \) -type f 2>/dev/null
        [[ -d "configs" ]] && find configs \( -name "*.yaml" -o -name "*.yml" \) -type f 2>/dev/null
    } | sed 's|^\./||' | sort -u | tee "$cache_file"
}


_xpcsjax() {
    local cur prev words cword
    _init_completion -s || return

    local opts="-h --help --config -c --output -o --output-format --mode --phi --multistart --no-multistart --multistart-n --max-iterations --tolerance --initial-D0 --initial-alpha --initial-D-offset --initial-gamma-dot-t0 --initial-gamma-dot-t-offset --initial-beta --initial-v-beta --initial-v0 --initial-v-offset --initial-phi0 --initial-f0 --initial-f1 --initial-f2 --initial-f3 --verbose -v --quiet -q --threads --no-jit --plot --no-plot --save-plots --plotting-backend --parallel-plots --phi-angles --plot-experimental-data --plot-simulated-data --contrast --offset-sim --version"

    case "$prev" in
        --config|-c)
            mapfile -t COMPREPLY < <(compgen -W "$(_xpcsjax_get_config_files)" -- "${cur}")
            return
            ;;
        --output|-o)
            _filedir -d
            return
            ;;
        --output-format)
            mapfile -t COMPREPLY < <(compgen -W "json npz both" -- "${cur}")
            return
            ;;
        --mode)
            mapfile -t COMPREPLY < <(compgen -W "static_anisotropic static_isotropic laminar_flow two_component" -- "${cur}")
            return
            ;;
        --threads)
            local cpu_count
            cpu_count=$(nproc 2>/dev/null || echo 4)
            mapfile -t COMPREPLY < <(compgen -W "1 2 4 8 ${cpu_count}" -- "${cur}")
            return
            ;;
        --plotting-backend)
            mapfile -t COMPREPLY < <(compgen -W "auto matplotlib datashader" -- "${cur}")
            return
            ;;
    esac

    if [[ "$cur" == -* ]]; then
        mapfile -t COMPREPLY < <(compgen -W "${opts}" -- "${cur}")
        return
    fi
}


_xpcsjax_config() {
    local cur prev words cword
    _init_completion -s || return

    local opts="-h --help --mode --output -o --data -d --q --dt --time-length --overwrite --show-template --validate -V --interactive -i"

    case "$prev" in
        --mode)
            mapfile -t COMPREPLY < <(compgen -W "static_anisotropic static_isotropic laminar_flow two_component" -- "${cur}")
            return
            ;;
        --output|-o)
            _filedir
            return
            ;;
        --data|-d)
            _filedir
            return
            ;;
    esac

    if [[ "$cur" == -* ]]; then
        mapfile -t COMPREPLY < <(compgen -W "${opts}" -- "${cur}")
        return
    fi
}


_xpcsjax_config_xla() {
    local cur prev words cword
    _init_completion -s || return

    local opts="-h --help --threads --no-x64 --debug --info"

    case "$prev" in
        --threads)
            local cpu_count
            cpu_count=$(nproc 2>/dev/null || echo 4)
            mapfile -t COMPREPLY < <(compgen -W "1 2 4 8 ${cpu_count}" -- "${cur}")
            return
            ;;
    esac

    if [[ "$cur" == -* ]]; then
        mapfile -t COMPREPLY < <(compgen -W "${opts}" -- "${cur}")
        return
    fi
}


_xpcsjax_post_install() {
    local cur prev words cword
    _init_completion -s || return

    local opts="-h --help --interactive -i --shell -s --no-completion --no-xla --xla-mode -v --verbose"

    case "$prev" in
        --shell|-s)
            mapfile -t COMPREPLY < <(compgen -W "bash zsh fish" -- "${cur}")
            return
            ;;
        --xla-mode)
            mapfile -t COMPREPLY < <(compgen -W "auto nlsq" -- "${cur}")
            return
            ;;
    esac

    if [[ "$cur" == -* ]]; then
        mapfile -t COMPREPLY < <(compgen -W "${opts}" -- "${cur}")
        return
    fi
}


_xpcsjax_cleanup() {
    local cur prev words cword
    _init_completion -s || return

    local opts="-h --help --dry-run -n --force -f --interactive -i -v --verbose"

    if [[ "$cur" == -* ]]; then
        mapfile -t COMPREPLY < <(compgen -W "${opts}" -- "${cur}")
        return
    fi
}


_xpcsjax_validate() {
    local cur prev words cword
    _init_completion -s || return

    local opts="-h --help -v --verbose --json"

    if [[ "$cur" == -* ]]; then
        mapfile -t COMPREPLY < <(compgen -W "${opts}" -- "${cur}")
        return
    fi
}


_xpcsjax_gui() {
    local cur prev words cword
    _init_completion -s || return

    local opts="-h --help --version"

    if [[ "$cur" == -* ]]; then
        mapfile -t COMPREPLY < <(compgen -W "${opts}" -- "${cur}")
        return
    fi
}


# Register completions
complete -F _xpcsjax xpcsjax
complete -F _xpcsjax xj
complete -F _xpcsjax xjexp
complete -F _xpcsjax xjsim
complete -F _xpcsjax_config xpcsjax-config
complete -F _xpcsjax_config xj-config
complete -F _xpcsjax_config_xla xpcsjax-config-xla
complete -F _xpcsjax_config_xla xj-config-xla
complete -F _xpcsjax_post_install xpcsjax-post-install
complete -F _xpcsjax_post_install xj-post-install
complete -F _xpcsjax_cleanup xpcsjax-cleanup
complete -F _xpcsjax_cleanup xj-cleanup
complete -F _xpcsjax_validate xpcsjax-validate
complete -F _xpcsjax_validate xj-validate
complete -F _xpcsjax_gui xpcsjax-gui
complete -F _xpcsjax_gui xj-gui
