"""Generate xpcsjax/runtime/shell/completion.sh from the CLI parsers.

The completion script is a DERIVED artifact: this module is the single writer.
Run ``python -m xpcsjax.runtime.shell.generate_completion`` to regenerate, or
``make completion``. A parity test fails CI if the committed file drifts.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from xpcsjax.runtime.shell.completion_spec import COMMAND_SPECS, CommandSpec, Hint


@dataclass(frozen=True)
class Completion:
    """How to complete the value of one option. kind drives the emitted bash."""

    kind: str  # configfile | file | dir | threads | words | choices | none
    payload: str = ""


def classify_option(action: argparse.Action, hints: dict[str, Hint]) -> Completion | None:
    """Classify one option into a value-completion descriptor.

    Parameters
    ----------
    action : argparse.Action
        The argparse action representing a single CLI option.
    hints : dict[str, Hint]
        Per-command completion hints keyed by flag string (e.g. ``"--output"``).
        Values are either a string keyword or a tuple/list of literal words.

    Returns
    -------
    Completion | None
        ``None`` for a zero-argument flag (``nargs == 0``). A ``Completion``
        describing the value completion otherwise. Raises ``ValueError`` for an
        unknown hint string — by construction the final fallback is ``"none"``
        so this only fires on future unknown hint strings.
    """
    # Zero-argument actions are flags: store_true/store_false/store_const/count/
    # version/help all set nargs == 0. Classify on nargs, never an allow-list.
    if action.nargs == 0:
        return None

    # Per-command dynamic hints take precedence over type-based inference.
    flag = action.option_strings[0] if action.option_strings else ""
    hint = _lookup_hint(list(action.option_strings), hints)
    if hint is not None:
        if isinstance(hint, (tuple, list)):  # literal word list
            return Completion(kind="words", payload=" ".join(hint))
        if hint in {"configfile", "file", "dir", "threads"}:
            return Completion(kind=hint)
        raise ValueError(f"unknown hint {hint!r} for {flag}")

    if action.choices:
        return Completion(kind="choices", payload=" ".join(str(c) for c in action.choices))

    if action.type is Path:
        return Completion(kind="file")

    # Takes a value but no completion source: emit nothing.
    return Completion(kind="none")


def _lookup_hint(option_strings: list[str], hints: dict[str, Hint]) -> Hint | None:
    """Return the first matching hint for any of the option's flag strings.

    Parameters
    ----------
    option_strings : list[str]
        All flag strings for the action (e.g. ``["-o", "--output"]``).
    hints : dict[str, Hint]
        Hint mapping keyed by flag string.

    Returns
    -------
    Hint | None
        The first matching hint, or ``None`` if none match.
    """
    for s in option_strings:
        if s in hints:
            return hints[s]
    return None


COMPLETION_SH_PATH = Path(__file__).with_name("completion.sh")

_BANNER = (
    "#!/bin/bash\n"
    "# GENERATED by generate_completion.py — DO NOT EDIT.\n"
    "# Regenerate with: make completion  (or python -m "
    "xpcsjax.runtime.shell.generate_completion)\n"
    "# Bash/zsh completion for xpcsjax CLI commands.\n"
)

# Static preamble: cache vars + _init_completion/_filedir fallback (bare
# conda/mamba shells) + cached config-file discovery. Copied verbatim from the
# historical completion.sh; byte-exact parity depends on this block being fixed.
_PREAMBLE = r"""
_XPCSJAX_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/xpcsjax"
_XPCSJAX_CACHE_TTL=300  # 5 minutes

if ! type mapfile &>/dev/null; then
    # ponytail: bash < 4 (e.g. macOS's stock /bin/bash 3.2) has no `mapfile`
    # builtin. Every completion arm below uses `mapfile -t NAME < <(cmd)`, so
    # shim that exact form once here rather than rewriting every call site.
    mapfile() {
        local __mapfile_arr=$2
        eval "$__mapfile_arr=()"
        local __mapfile_line
        while IFS= read -r __mapfile_line; do
            eval "$__mapfile_arr+=(\"\$__mapfile_line\")"
        done
        unset __mapfile_line
    }
fi

_xpcsjax_ensure_cache() {
    [[ -d "$_XPCSJAX_CACHE_DIR" ]] || mkdir -p "$_XPCSJAX_CACHE_DIR"
}

if ! type _init_completion &>/dev/null; then
    _init_completion() {
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    }

    if ! type _filedir &>/dev/null; then
        _filedir() {
            if [[ "$1" == "-d" ]]; then
                mapfile -t COMPREPLY < <(compgen -d -- "${cur}")
            else
                mapfile -t COMPREPLY < <(compgen -f -- "${cur}")
            fi
        }
    fi
fi

_xpcsjax_get_config_files() {
    _xpcsjax_ensure_cache
    # Key the cache file by cwd so a completion cached for one project's
    # config files is never served for a different directory within the TTL.
    local cache_file="$_XPCSJAX_CACHE_DIR/config_files_${PWD//\//_}"
    local now
    now=$(date +%s)

    if [[ -f "$cache_file" ]]; then
        local cache_time
        cache_time=$(stat -f %m "$cache_file" 2>/dev/null || stat -c %Y "$cache_file" 2>/dev/null)
        if [[ $((now - cache_time)) -lt $_XPCSJAX_CACHE_TTL ]]; then
            cat "$cache_file"
            return
        fi
    fi

    {
        find . -maxdepth 2 \( -name "*.yaml" -o -name "*.yml" \) -type f 2>/dev/null
        [[ -d "config" ]] && find config \( -name "*.yaml" -o -name "*.yml" \) -type f 2>/dev/null
        [[ -d "configs" ]] && find configs \( -name "*.yaml" -o -name "*.yml" \) -type f 2>/dev/null
    } | sort -u | tee "$cache_file"
}
"""


def _all_option_strings(parser: argparse.ArgumentParser) -> list[str]:
    """All option strings in declaration order (includes -h/--help)."""
    out: list[str] = []
    for action in parser._actions:
        out.extend(action.option_strings)
    return out


def _value_completion_bash(comp: Completion) -> str:
    """Bash body that fills COMPREPLY for an option that takes a value."""
    if comp.kind == "configfile":
        return 'mapfile -t COMPREPLY < <(compgen -W "$(_xpcsjax_get_config_files)" -- "${cur}")'
    if comp.kind == "dir":
        return "_filedir -d"
    if comp.kind == "file":
        return "_filedir"
    if comp.kind == "words" or comp.kind == "choices":
        return f'mapfile -t COMPREPLY < <(compgen -W "{comp.payload}" -- "${{cur}}")'
    if comp.kind == "threads":
        # Un-indented lines; _emit_function indents continuation lines to 12.
        return (
            "local cpu_count\n"
            "cpu_count=$(nproc 2>/dev/null || echo 4)\n"
            'mapfile -t COMPREPLY < <(compgen -W "1 2 4 8 ${cpu_count}" -- "${cur}")'
        )
    return ""  # kind == "none": no value hint


def _emit_function(spec: CommandSpec) -> str:
    parser = spec.parser_factory()
    opts = " ".join(_all_option_strings(parser))

    # Build per-prev value-completion case arms (skip kind == "none").
    arms: list[str] = []
    for action in parser._actions:
        if not action.option_strings:
            continue
        comp = classify_option(action, spec.dynamic_hints)
        if comp is None or comp.kind == "none":
            continue
        pattern = "|".join(action.option_strings)
        # Indent continuation lines to 12 spaces. The "threads" body is
        # multi-line; the f-string only indents its first line, so join the
        # remaining lines with newline+12-spaces. (Single-line bodies are
        # unaffected — splitlines() yields one element.)
        body = "\n            ".join(_value_completion_bash(comp).splitlines())
        arms.append(f"        {pattern})\n            {body}\n            return\n            ;;")

    case_block = ""
    if arms:
        case_block = '    case "$prev" in\n' + "\n".join(arms) + "\n    esac\n\n"

    return (
        f"{spec.completion_func}() {{\n"
        "    local cur prev words cword\n"
        "    _init_completion -s || return\n\n"
        f'    local opts="{opts}"\n\n'
        f"{case_block}"
        '    if [[ "$cur" == -* ]]; then\n'
        '        mapfile -t COMPREPLY < <(compgen -W "${opts}" -- "${cur}")\n'
        "        return\n"
        "    fi\n"
        "}\n"
    )


def _emit_footer() -> str:
    lines = ["# Register completions"]
    for spec in COMMAND_SPECS:
        for name in spec.command_names:
            lines.append(f"complete -F {spec.completion_func} {name}")
    return "\n".join(lines) + "\n"


def generate() -> str:
    """Return the full completion.sh text."""
    parts = [_BANNER, _PREAMBLE, ""]
    for spec in COMMAND_SPECS:
        parts.append(_emit_function(spec))
        parts.append("")
    parts.append(_emit_footer())
    return "\n".join(parts)


def main() -> None:
    """Write the generated completion script to ``completion.sh``."""
    COMPLETION_SH_PATH.write_text(generate(), encoding="utf-8")
    print(f"wrote {COMPLETION_SH_PATH}")


if __name__ == "__main__":
    main()
