"""Shared synthetic heterodyne fixtures for optimization unit tests.

The model + data construction mirrors ``tests/integration/test_heterodyne_fit_smoke.py``
verbatim (config dict, ConfigManager -> HeterodyneModel.from_config, and the
per-angle ``model.compute_correlation`` stack), parameterized by ``n_phi`` and
``n_t`` so unit tests can build self-consistent two-component data at the
model's initial parameters.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import numpy as np

_DT = 1.0
_Q = 0.0054
_NOISE = 5e-4


def _config_dict(n_phi: int, n_t: int) -> dict:
    return {
        "analysis_mode": "two_component",
        "analyzer_parameters": {
            "dt": _DT,
            "start_frame": 1,
            "end_frame": n_t,
            "scattering": {"wavevector_q": _Q},
        },
        "scaling": {
            "n_angles": n_phi,
            "mode": "constant",
            "initial_contrast": 0.3,
            "initial_offset": 1.0,
        },
        "optimization": {
            "nlsq": {
                "analysis_mode": "two_component",
                "max_iterations": 30,
                "enable_cmaes": False,
            },
        },
    }


def make_synthetic_two_component(n_phi: int = 3, n_t: int = 12):
    """Build a configured HeterodyneModel plus self-consistent synthetic data.

    Returns ``(model, c2, phi)`` where:

    * ``model`` is a ``HeterodyneModel`` in ``two_component`` mode,
    * ``c2`` is a ``(n_phi, n_t, n_t)`` float64 array generated by
      ``model.compute_correlation`` at the model's initial params (+ tiny noise),
    * ``phi`` is a ``(n_phi,)`` float64 array of angles in degrees.
    """
    import yaml

    from xpcsjax.config import ConfigManager
    from xpcsjax.core.heterodyne_model_stateful import HeterodyneModel

    phi = np.linspace(0.0, 150.0, n_phi, dtype=np.float64)

    with tempfile.TemporaryDirectory() as tmp_dir:
        cfg_path = Path(tmp_dir) / "fixture.yaml"
        cfg_path.write_text(yaml.safe_dump(_config_dict(n_phi, n_t)))
        cfg = ConfigManager(str(cfg_path))
        assert cfg.config is not None
        model = HeterodyneModel.from_config(cfg.config)

    rng = np.random.default_rng(seed=20260524)
    c2 = np.empty((n_phi, n_t, n_t), dtype=np.float64)
    for i, phi_angle in enumerate(phi):
        corr = np.asarray(model.compute_correlation(phi_angle=float(phi_angle), angle_idx=i))
        c2[i] = corr + rng.normal(0.0, _NOISE, size=corr.shape)

    return model, c2, phi
