"""Shared synthetic heterodyne fixtures for optimization unit tests.

The model + data construction mirrors ``tests/integration/test_heterodyne_fit_smoke.py``
verbatim (config dict, ConfigManager -> HeterodyneModel.from_config, and the
per-angle ``model.compute_correlation`` stack), parameterized by ``n_phi`` and
``n_t`` so unit tests can build self-consistent two-component data at the
model's initial parameters.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import numpy as np

_DT = 1.0
_Q = 0.0054
_NOISE = 5e-4
# The registry default f1 = 0 puts the fixture on a structurally singular point
# of the fraction model f0*exp(f1*(t - f2)) + f3: the f2 column of the Jacobian
# is exactly zero and f0/f3 are exactly collinear. A solver that converges right
# at x0 then hands finalize_covariance an exact-zero variance and the whole
# covariance is (correctly) the NaN placeholder — CI run 35005275832
# (2026-09-15) did exactly that on every macOS job while Linux drifted off x0
# first and passed by rounding luck. Seed f1 off zero so the fixture's
# covariance is a real estimate on every platform; with dt = 1 and n_t <= 20
# the fraction stays inside smooth_clip's (0, 1). Pinned by
# tests/optimization/test_heterodyne_fixtures_sanity.py.
_F1 = 0.02


def _config_dict(n_phi: int, n_t: int, stratification: dict | None = None) -> dict:
    optimization: dict = {
        "nlsq": {
            "analysis_mode": "two_component",
            "max_iterations": 30,
            "enable_cmaes": False,
        },
    }
    if stratification is not None:
        optimization["stratification"] = stratification
    return {
        "analysis_mode": "two_component",
        "analyzer_parameters": {
            "dt": _DT,
            "start_frame": 1,
            "end_frame": n_t,
            "scattering": {"wavevector_q": _Q},
        },
        "scaling": {
            "n_angles": n_phi,
            "mode": "constant",
            "initial_contrast": 0.3,
            "initial_offset": 1.0,
        },
        "parameters": {"fraction": {"f1": {"value": _F1}}},  # see _F1
        "optimization": optimization,
    }


def _build_cfgmgr(n_phi: int, n_t: int, stratification: dict | None = None):
    """Construct a real ``ConfigManager`` for a two-component fixture config.

    The temp YAML is written, loaded, and discarded; the returned manager keeps
    its parsed ``.config`` dict in memory (the file is no longer needed once the
    manager has parsed it).
    """
    import yaml

    from xpcsjax.config import ConfigManager

    with tempfile.TemporaryDirectory() as tmp_dir:
        cfg_path = Path(tmp_dir) / "fixture.yaml"
        cfg_path.write_text(yaml.safe_dump(_config_dict(n_phi, n_t, stratification)))
        cfg = ConfigManager(str(cfg_path))
    assert cfg.config is not None
    return cfg


def make_synthetic_two_component(n_phi: int = 3, n_t: int = 12):
    """Build a configured HeterodyneModel plus self-consistent synthetic data.

    Returns ``(model, c2, phi)`` where:

    * ``model`` is a ``HeterodyneModel`` in ``two_component`` mode,
    * ``c2`` is a ``(n_phi, n_t, n_t)`` float64 array generated by
      ``model.compute_correlation`` at the model's initial params (+ tiny noise),
    * ``phi`` is a ``(n_phi,)`` float64 array of angles in degrees.
    """
    from xpcsjax.core.heterodyne_model_stateful import HeterodyneModel

    phi = np.linspace(0.0, 150.0, n_phi, dtype=np.float64)

    cfg = _build_cfgmgr(n_phi, n_t)
    model = HeterodyneModel.from_config(cfg.config)

    rng = np.random.default_rng(seed=20260524)
    c2 = np.empty((n_phi, n_t, n_t), dtype=np.float64)
    for i, phi_angle in enumerate(phi):
        corr = np.asarray(model.compute_correlation(phi_angle=float(phi_angle), angle_idx=i))
        c2[i] = corr + rng.normal(0.0, _NOISE, size=corr.shape)

    return model, c2, phi


def make_cfgmgr_and_data(n_phi: int, n_t: int, stratification: dict | None = None):
    """Build a real ``ConfigManager`` plus a heterodyne-loader data dict.

    Returns ``(cfg, data)`` where:

    * ``cfg`` is a ``ConfigManager`` in ``two_component`` mode (the same config
      used by :func:`make_synthetic_two_component`),
    * ``data`` is ``{"c2_exp": <(n_phi, n_t, n_t) array>, "phi_angles_list": <phi>}``,
      the key names the heterodyne dispatch (``_fit_nlsq_heterodyne``) accepts.

    The synthetic ``c2`` stack is self-consistent with the config's model so the
    dispatch path runs end-to-end through ``fit_nlsq`` without raising.
    """
    model, c2, phi = make_synthetic_two_component(n_phi=n_phi, n_t=n_t)
    cfg = _build_cfgmgr(n_phi, n_t, stratification)
    data = {"c2_exp": c2, "phi_angles_list": phi}
    return cfg, data
