"""Tests for heterodyne stratified hybrid-streaming pipeline (Phase 2)."""

from __future__ import annotations

import numpy as np
import pytest


def _make_synthetic_heterodyne(n_phi: int = 2, n_t: int = 8, seed: int = 0):
    """Build a tiny synthetic heterodyne dataset from the live kernel.

    Returns (model, c2, phi) where c2 has shape (n_phi, n_t, n_t) and
    is generated by the real compute_c2_heterodyne kernel at the model's
    initial parameters, so residual should be ~0 at those parameters.
    """
    import jax.numpy as jnp

    from xpcsjax.config import ConfigManager
    from xpcsjax.core.heterodyne_jax_backend import compute_c2_heterodyne
    from xpcsjax.core.heterodyne_model_stateful import HeterodyneModel

    cfg = ConfigManager("xpcsjax/config/templates/xpcsjax_two_component.yaml")
    model = HeterodyneModel.from_config(cfg.config)

    t = np.arange(1, n_t + 1, dtype=np.float64) * model.dt
    model.sync_time_axis(t)

    phi = np.linspace(-5.0, 5.0, n_phi).astype(np.float64)
    full = jnp.asarray(model.param_manager.get_full_values(), dtype=jnp.float64)
    contrast, offset = model.scaling.get_for_angle(0)

    c2 = np.stack(
        [
            np.asarray(
                compute_c2_heterodyne(full, model.t, model.q, model.dt, float(p), contrast, offset)
            )
            for p in phi
        ]
    )  # shape: (n_phi, n_t, n_t)

    return model, c2, phi


def test_model_fn_pointwise_matches_kernel():
    """model_fn must reproduce the meshgrid c2 per point using the SAME per-angle
    scaling it computed (decoupled from scaling estimation accuracy)."""
    import jax.numpy as jnp

    from xpcsjax.core.heterodyne_jax_backend import compute_c2_heterodyne
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        build_heterodyne_pointwise_model,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=2, n_t=8)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    model_fn, x_data, y_data, p0, meta = build_heterodyne_pointwise_model(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
    )
    phi_unique = np.asarray(meta["phi_unique"])
    contrast_arr = np.asarray(meta["contrast_arr"])
    offset_arr = np.asarray(meta["offset_arr"])
    full = np.asarray(model.param_manager.get_full_values())

    pred = np.asarray(model_fn(jnp.asarray(x_data), *[jnp.asarray(v) for v in p0]))

    # Expected: per-point meshgrid c2 with the SAME scaling meta reports.
    meshes = [
        np.asarray(
            compute_c2_heterodyne(
                jnp.asarray(full),
                model.t,
                model.q,
                model.dt,
                float(phi_unique[a]),
                float(contrast_arr[a]),
                float(offset_arr[a]),
            )
        )
        for a in range(len(phi_unique))
    ]
    expected = np.array(
        [
            meshes[int(x_data[k, 0])][int(x_data[k, 1]), int(x_data[k, 2])]
            for k in range(x_data.shape[0])
        ]
    )
    assert np.max(np.abs(pred - expected)) < 1e-6, f"max diff {np.max(np.abs(pred - expected)):.3e}"


def test_fit_with_stratified_hybrid_streaming_heterodyne_dispatch(monkeypatch):
    import xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming as hs
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )

    captured = {}

    class _FakeOpt:
        def __init__(self, config):
            captured["config"] = config

        def fit(self, data_source, func, p0, bounds=None, sigma=None, **kw):
            captured["n_params"] = len(p0)
            captured["has_func"] = callable(func)
            n = len(p0)
            return {
                "x": np.zeros(n),
                "pcov": np.eye(n),
                "perr": np.zeros(n),
                "nit": 5,
                "success": True,
            }

    monkeypatch.setattr(hs, "AdaptiveHybridStreamingOptimizer", _FakeOpt)

    model, c2, phi = _make_synthetic_heterodyne()
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lower, upper = model.param_manager.get_bounds()
    popt, pcov, info = hs.fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values()),
        bounds=(np.asarray(lower), np.asarray(upper)),
        hybrid_config={"enable": True, "warmup_iterations": 30, "chunk_size": 4000},
        # Pin constant so popt stays physics-only (this test targets config
        # pass-through / dispatch, not the scaling mode). The default is now 'auto'.
        anti_degeneracy_config={"per_angle_mode": "constant"},
    )
    assert popt.shape[0] == model.param_manager.n_varying
    assert pcov.shape == (popt.shape[0], popt.shape[0])
    assert info["nit"] == 5
    assert captured["config"].warmup_iterations == 30
    assert captured["config"].chunk_size == 4000
    assert captured["has_func"] is True


def test_build_hybrid_streaming_result():
    from xpcsjax.optimization.nlsq.heterodyne_result_builder import build_hybrid_streaming_result

    model, c2, phi = _make_synthetic_heterodyne()
    n = model.param_manager.n_varying
    res = build_hybrid_streaming_result(
        model=model,
        popt=np.zeros(n),
        pcov=np.eye(n),
        info={"nit": 4, "success": True, "hybrid_streaming_diagnostics": {"phase": "done"}},
        phi_angles=phi,
    )
    assert hasattr(res, "parameters")
    assert isinstance(res.nlsq_diagnostics, dict)
    assert res.nlsq_diagnostics["hybrid_streaming"]["phase"] == "done"
    assert res.nlsq_diagnostics.get("shear_weighting") == "not_applicable_heterodyne"


def test_build_hybrid_streaming_result_dof_fallback_on_missing_varying_names(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Debt #1 regression: if ``model.param_manager.varying_names`` raises
    ``AttributeError``, the reduced-chi2 DOF calc must degrade gracefully to
    ``len(popt)`` rather than crash result assembly for an otherwise-
    successful fit (this block is a cosmetic DOF display value)."""
    from xpcsjax.optimization.nlsq.heterodyne_result_builder import build_hybrid_streaming_result

    model, _c2, phi = _make_synthetic_heterodyne()
    n = model.param_manager.n_varying
    # Capture before monkeypatching: the builder has an EARLIER, unguarded
    # ``varying_names`` read for the ``parameter_names`` default (line ~573)
    # that must be bypassed via an explicit ``parameter_names=`` so this test
    # isolates the guarded DOF-fallback site (line ~674) it targets.
    param_names = list(model.param_manager.varying_names)

    def _raise_attribute_error(self: object) -> None:
        raise AttributeError("varying_names unavailable (simulated)")

    monkeypatch.setattr(
        type(model.param_manager), "varying_names", property(_raise_attribute_error)
    )

    res = build_hybrid_streaming_result(
        model=model,
        popt=np.zeros(n),
        pcov=np.eye(n),
        info={
            "nit": 4,
            "success": True,
            "n_data_points": 1000,
            "anti_degeneracy": {"per_angle_mode": "constant"},
        },
        phi_angles=phi,
        parameter_names=param_names,
    )
    assert hasattr(res, "parameters")
    assert np.isfinite(res.reduced_chi_squared)


def test_build_hybrid_streaming_result_max_nfev_is_max_iter_not_failed():
    """A solve that exhausts ``max_nfev`` but lands on a good fit must report
    ``convergence_status='max_iter'`` and grade quality from the real reduced
    chi^2 — NOT a blanket ``'failed'`` / ``'poor'``.

    Root cause (C044 two_component, 2026-06-07 log): the trust-region solver hit
    SciPy's default ``max_nfev = 100*n_params`` before certifying ``gtol`` yet
    produced reduced chi^2 ~= 0.68 (a good fit). The builder hardcoded
    ``quality_flag = '...' if success else 'poor'`` and
    ``convergence_status = 'converged' if success else 'failed'``, mislabeling a
    usable fit as a hard failure. The driver now threads the SciPy termination
    reason so the builder can distinguish "budget exhausted" from "diverged".
    """
    from xpcsjax.optimization.nlsq.heterodyne_result_builder import (
        build_hybrid_streaming_result,
    )

    model, _c2, phi = _make_synthetic_heterodyne()
    n = model.param_manager.n_varying
    ssr = 10.0
    n_data = 1000
    sigma2 = 0.01  # reduced chi^2 ~= 10 / (0.01 * (1000 - n)) ~= 1.0 -> "good"
    res = build_hybrid_streaming_result(
        model=model,
        popt=np.zeros(n),
        pcov=np.eye(n),
        info={
            "nit": 1513,
            "success": False,
            "convergence_reason": "Maximum function evaluations reached",
            "cost": 0.5 * ssr,
            "n_data_points": n_data,
            "sigma2_noise": sigma2,
        },
        phi_angles=phi,
    )
    assert res.reduced_chi_squared < 2.0
    assert res.convergence_status == "max_iter"
    assert res.quality_flag == "good"


def test_build_hybrid_streaming_result_genuine_failure_stays_failed_poor():
    """Regression guard: a genuine non-convergence (no max_nfev reason, or a bad
    reason) with success=False must STILL map to ``'failed'`` / ``'poor'`` — the
    max_iter relaxation is scoped strictly to the max-function-evaluations case.
    """
    from xpcsjax.optimization.nlsq.heterodyne_result_builder import (
        build_hybrid_streaming_result,
    )

    model, _c2, phi = _make_synthetic_heterodyne()
    n = model.param_manager.n_varying
    ssr = 10.0
    res = build_hybrid_streaming_result(
        model=model,
        popt=np.zeros(n),
        pcov=np.eye(n),
        info={
            "nit": 3,
            "success": False,
            "convergence_reason": "Improper input parameters",
            "cost": 0.5 * ssr,
            "n_data_points": 1000,
            "sigma2_noise": 0.01,
        },
        phi_angles=phi,
    )
    assert res.convergence_status == "failed"
    assert res.quality_flag == "poor"


def test_build_hybrid_streaming_result_noise_normalized_reduced_chi2():
    """reduced_chi_squared must be noise-normalized (≈1 scale) when the driver
    threads ``info['sigma2_noise']`` — mirroring the in-memory averaged/individual
    joint paths. Prevents the meaningless ``MSE ≪ 1`` value the stratified-LS
    path reported before (smart-debug RCA: χ²_red = 0.0024 on C020 two_component).
    """
    from xpcsjax.optimization.nlsq.heterodyne_result_builder import (
        build_hybrid_streaming_result,
    )

    model, _c2, phi = _make_synthetic_heterodyne()
    n = model.param_manager.n_varying
    ssr = 100.0
    n_data = 1000
    sigma2 = 0.01
    res = build_hybrid_streaming_result(
        model=model,
        popt=np.zeros(n),
        pcov=np.eye(n),
        info={
            "nit": 4,
            "success": True,
            "cost": 0.5 * ssr,
            "n_data_points": n_data,
            "sigma2_noise": sigma2,
        },
        phi_angles=phi,
    )
    n_dof = max(1, n_data - n)
    assert res.reduced_chi_squared == pytest.approx(ssr / (sigma2 * n_dof))


def test_build_hybrid_streaming_result_mse_fallback_without_sigma2():
    """Backward-compat: with no ``sigma2_noise`` threaded (degenerate noise /
    legacy callers) the builder falls back to plain ``MSE = SSR/dof`` exactly as
    before, so existing callers are unaffected."""
    from xpcsjax.optimization.nlsq.heterodyne_result_builder import (
        build_hybrid_streaming_result,
    )

    model, _c2, phi = _make_synthetic_heterodyne()
    n = model.param_manager.n_varying
    ssr = 100.0
    n_data = 1000
    res = build_hybrid_streaming_result(
        model=model,
        popt=np.zeros(n),
        pcov=np.eye(n),
        info={"nit": 4, "success": True, "cost": 0.5 * ssr, "n_data_points": n_data},
        phi_angles=phi,
    )
    n_dof = max(1, n_data - n)
    assert res.reduced_chi_squared == pytest.approx(ssr / n_dof)


def test_build_hybrid_streaming_result_quality_reflects_reduced_chi2():
    """quality_flag must classify from the real noise-normalized reduced_chi2,
    not a hardcoded 1.0 — a genuinely bad fit (large χ²_red) must not report
    'good' merely because the optimizer reported success."""
    from xpcsjax.optimization.nlsq.heterodyne_result_builder import (
        build_hybrid_streaming_result,
    )

    model, _c2, phi = _make_synthetic_heterodyne()
    n = model.param_manager.n_varying
    ssr = 100.0
    n_data = 1000
    sigma2 = 1e-4  # -> reduced_chi2 ~ 1e6/(n_data-n) >> 5 (poor band)
    res = build_hybrid_streaming_result(
        model=model,
        popt=np.zeros(n),
        pcov=np.eye(n),
        info={
            "nit": 4,
            "success": True,
            "cost": 0.5 * ssr,
            "n_data_points": n_data,
            "sigma2_noise": sigma2,
        },
        phi_angles=phi,
    )
    assert res.reduced_chi_squared > 5.0
    assert res.quality_flag == "poor"


def test_build_hybrid_streaming_result_uses_driver_ssr_not_missing_cost():
    """The builder must honor the driver-computed authoritative ``info['ssr']``.

    The production driver (heterodyne_hybrid_streaming.py) threads the real SSR
    under ``info['ssr']`` (and NOT ``info['cost']``). The L2/individual
    hierarchical branch builds ``info`` manually with no ``'cost'`` key, so
    reading ``info.get('cost', 0.0)`` silently yielded ``ssr=0`` ->
    ``chi_squared=0`` -> ``reduced_chi2=0`` -> ``quality_flag='good'`` on a real
    converged fit (a false success). Unit tests masked it by feeding a synthetic
    ``'cost'`` key that production never sets.
    """
    from xpcsjax.optimization.nlsq.heterodyne_result_builder import (
        build_hybrid_streaming_result,
    )

    model, _c2, phi = _make_synthetic_heterodyne()
    n = model.param_manager.n_varying
    ssr = 100.0
    n_data = 1000
    sigma2 = 1e-4  # large reduced chi2 -> must classify "poor", not "good"
    # Production-shaped info: 'ssr' present, NO 'cost' (mirrors the L2 branch).
    res = build_hybrid_streaming_result(
        model=model,
        popt=np.zeros(n),
        pcov=np.eye(n),
        info={
            "nit": 4,
            "success": True,
            "ssr": ssr,
            "n_data_points": n_data,
            "sigma2_noise": sigma2,
        },
        phi_angles=phi,
    )
    assert res.chi_squared == pytest.approx(ssr), (
        f"chi_squared must reflect the driver SSR ({ssr}), not a missing-'cost' "
        f"default of 0; got {res.chi_squared}"
    )
    assert res.quality_flag == "poor", (
        f"a large-SSR fit must not falsely report 'good'; got {res.quality_flag}"
    )


# ---------------------------------------------------------------------------
# Phase 2 Task 4: dispatch gate tests
# ---------------------------------------------------------------------------


def _install_model_stub(monkeypatch, model):
    import sys
    import types

    fake_mod = types.ModuleType("xpcsjax.core.heterodyne_model_stateful")

    class _M:
        @classmethod
        def from_config(cls, _cfg):
            return model

    fake_mod.HeterodyneModel = _M
    monkeypatch.setitem(sys.modules, "xpcsjax.core.heterodyne_model_stateful", fake_mod)


class _Cfg:
    def __init__(self, c):
        self.config = c


def test_hybrid_fires_on_streaming_tier(monkeypatch):
    import xpcsjax.optimization.nlsq as nlsq_pkg
    from xpcsjax.optimization.nlsq import heterodyne_memory as hm

    model, c2, phi = _make_synthetic_heterodyne()
    _install_model_stub(monkeypatch, model)

    # Force tier = STREAMING
    class _Dec:
        strategy = hm.NLSQStrategy.STREAMING
        peak_memory_gb = 99.0
        threshold_gb = 1.0

    monkeypatch.setattr(hm, "select_nlsq_strategy", lambda *a, **k: _Dec())

    called = {}
    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming.fit_with_stratified_hybrid_streaming_heterodyne",
        lambda **k: (
            called.setdefault("yes", True),
            (
                __import__("numpy").zeros(model.param_manager.n_varying),
                __import__("numpy").eye(model.param_manager.n_varying),
                {"nit": 1, "success": True},
            ),
        )[1],
    )
    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.heterodyne_core.fit_nlsq_multi_phi",
        lambda *a, **k: (_ for _ in ()).throw(
            AssertionError("joint path must not run when hybrid fires")
        ),
    )

    cfg = _Cfg(
        {
            "analysis_mode": "two_component",
            "optimization": {"nlsq": {"hybrid_streaming": {"enable": True}}},
        }
    )
    data = {"c2_exp": c2, "phi_angles_list": phi}
    nlsq_pkg.fit_nlsq(data, cfg)
    assert called.get("yes") is True


def test_hybrid_does_not_fire_on_standard_tier(monkeypatch):
    import xpcsjax.optimization.nlsq as nlsq_pkg
    from xpcsjax.optimization.nlsq import heterodyne_memory as hm

    model, c2, phi = _make_synthetic_heterodyne()
    _install_model_stub(monkeypatch, model)

    class _Dec:
        strategy = hm.NLSQStrategy.STANDARD
        peak_memory_gb = 0.1
        threshold_gb = 1.0

    monkeypatch.setattr(hm, "select_nlsq_strategy", lambda *a, **k: _Dec())

    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming.fit_with_stratified_hybrid_streaming_heterodyne",
        lambda **k: (_ for _ in ()).throw(AssertionError("hybrid must NOT fire on STANDARD tier")),
    )
    joint = {}
    import numpy as _np

    class _R:
        parameters = _np.zeros(1)
        chi_squared = 0.0
        reduced_chi_squared = 0.0
        success = True
        message = "ok"
        nlsq_diagnostics: dict = {}

    # The standard (non-hybrid) in-memory path for an in-scope two_component mode
    # now lands on the SHARED engine route (Task #16b) first, falling back to
    # fit_nlsq_multi_phi only on a routing skip. Record BOTH so the assertion
    # captures "fell through to the normal joint fit" regardless of which standard
    # sink ran — the real "hybrid must NOT fire" guard is the throw-patch above.
    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.heterodyne_core.fit_nlsq_multi_phi",
        lambda *a, **k: joint.setdefault("yes", True) or _R(),
    )
    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.heterodyne_engine_route.fit_two_component_via_engine",
        lambda *a, **k: joint.setdefault("yes", True) or _R(),
    )

    cfg = _Cfg(
        {
            "analysis_mode": "two_component",
            "optimization": {"nlsq": {"hybrid_streaming": {"enable": True}}},
        }
    )
    data = {"c2_exp": c2, "phi_angles_list": phi}
    nlsq_pkg.fit_nlsq(data, cfg)
    assert joint.get("yes") is True  # fell through to the normal joint fit


def test_cmaes_precedence_over_hybrid(monkeypatch):
    import xpcsjax.optimization.nlsq as nlsq_pkg
    from xpcsjax.optimization.nlsq import heterodyne_memory as hm

    model, c2, phi = _make_synthetic_heterodyne()
    _install_model_stub(monkeypatch, model)

    class _Dec:
        strategy = hm.NLSQStrategy.STREAMING
        peak_memory_gb = 99.0
        threshold_gb = 1.0

    monkeypatch.setattr(hm, "select_nlsq_strategy", lambda *a, **k: _Dec())

    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming.fit_with_stratified_hybrid_streaming_heterodyne",
        lambda **k: (_ for _ in ()).throw(AssertionError("hybrid must not run when cmaes on")),
    )
    import numpy as _np

    class _R:
        parameters = _np.zeros(1)
        chi_squared = 0.0
        reduced_chi_squared = 0.0
        success = True
        message = "ok"
        nlsq_diagnostics: dict = {}

    joint = {}
    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.heterodyne_core.fit_nlsq_multi_phi",
        lambda *a, **k: joint.setdefault("yes", True) or _R(),
    )
    cfg = _Cfg(
        {
            "analysis_mode": "two_component",
            "optimization": {
                "nlsq": {"cmaes": {"enable": True}, "hybrid_streaming": {"enable": True}}
            },
        }
    )
    data = {"c2_exp": c2, "phi_angles_list": phi}
    nlsq_pkg.fit_nlsq(data, cfg)
    assert joint.get("yes") is True


def test_flat_multistart_skips_engine_route_on_auto_budget(monkeypatch):
    """A flat ``multistart=True`` fit with the default auto budget must NOT route
    through the engine route (which runs no global escape) — it must fall through
    to fit_nlsq_multi_phi, which owns the joint multistart escape. Regression for
    the Codex finding that the engine-route gate only checked ``cmaes_on``.
    """
    import xpcsjax.optimization.nlsq as nlsq_pkg

    model, c2, phi = _make_synthetic_heterodyne()
    _install_model_stub(monkeypatch, model)

    # The engine route must NEVER run when a global escape is requested.
    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.heterodyne_engine_route.fit_two_component_via_engine",
        lambda *a, **k: (_ for _ in ()).throw(
            AssertionError("engine route must not run when flat multistart is on")
        ),
    )
    import numpy as _np

    class _R:
        parameters = _np.zeros(1)
        chi_squared = 0.0
        reduced_chi_squared = 0.0
        success = True
        message = "ok"
        nlsq_diagnostics: dict = {}

    joint = {}
    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.heterodyne_core.fit_nlsq_multi_phi",
        lambda *a, **k: joint.setdefault("yes", True) or _R(),
    )

    cfg = _Cfg(
        {
            "analysis_mode": "two_component",
            "optimization": {"nlsq": {"multistart": True}},
        }
    )
    data = {"c2_exp": c2, "phi_angles_list": phi}
    # Self-validating: if flat ``multistart`` were NOT parsed onto nlsq_cfg the
    # gate would not fire, the engine route would run, and its monkeypatched stub
    # would raise. A clean pass proves both the parse and the gate.
    nlsq_pkg.fit_nlsq(data, cfg)
    assert joint.get("yes") is True  # routed to fit_nlsq_multi_phi (owns the escape)


def test_flat_multistart_precedence_over_hybrid(monkeypatch):
    """Flat ``multistart=True`` + hybrid_streaming.enable=True at a streaming tier
    must NOT take the hybrid local path — it must fall through to
    fit_nlsq_multi_phi, which owns the joint multistart escape.

    Regression for the Codex finding that the hybrid-streaming gate only checked
    ``cmaes_on``: the flat ``multistart`` escape (like CMA-ES, owned by
    fit_nlsq_multi_phi) was silently intercepted on LARGE/STREAMING data, so a
    large two_component fit shipped a different optimizer than configured. Mirror
    of ``test_cmaes_precedence_over_hybrid``.
    """
    import xpcsjax.optimization.nlsq as nlsq_pkg
    from xpcsjax.optimization.nlsq import heterodyne_memory as hm

    model, c2, phi = _make_synthetic_heterodyne()
    _install_model_stub(monkeypatch, model)

    class _Dec:
        strategy = hm.NLSQStrategy.STREAMING
        peak_memory_gb = 99.0
        threshold_gb = 1.0

    monkeypatch.setattr(hm, "select_nlsq_strategy", lambda *a, **k: _Dec())

    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming.fit_with_stratified_hybrid_streaming_heterodyne",
        lambda **k: (_ for _ in ()).throw(
            AssertionError("hybrid must not run when flat multistart is on")
        ),
    )
    # The engine route runs no global escape, so it must also be skipped when a
    # flat multistart is requested (already gated; guard it so a regression here
    # surfaces too).
    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.heterodyne_engine_route.fit_two_component_via_engine",
        lambda *a, **k: (_ for _ in ()).throw(
            AssertionError("engine route must not run when flat multistart is on")
        ),
    )
    import numpy as _np

    class _R:
        parameters = _np.zeros(1)
        chi_squared = 0.0
        reduced_chi_squared = 0.0
        success = True
        message = "ok"
        nlsq_diagnostics: dict = {}

    joint = {}
    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.heterodyne_core.fit_nlsq_multi_phi",
        lambda *a, **k: joint.setdefault("yes", True) or _R(),
    )
    cfg = _Cfg(
        {
            "analysis_mode": "two_component",
            "optimization": {"nlsq": {"multistart": True, "hybrid_streaming": {"enable": True}}},
        }
    )
    data = {"c2_exp": c2, "phi_angles_list": phi}
    nlsq_pkg.fit_nlsq(data, cfg)
    assert joint.get("yes") is True  # routed to fit_nlsq_multi_phi (owns the escape)


def test_flat_multistart_skips_stratified_ls(monkeypatch):  # noqa: N802 - "1M" pins the boundary
    """Flat ``multistart=True`` + >=1M points must NOT take the stratified-LS local
    path — it must fall through to fit_nlsq_multi_phi, which owns the joint
    multistart escape.

    Regression for the Codex finding that the >=1M stratified-LS gate only checked
    ``cmaes_on``, silently dropping the flat multistart escape on large data.
    Mirror of ``test_flat_enable_cmaes_skips_stratified_ls``.
    """
    import xpcsjax.optimization.nlsq as nlsq_pkg
    import xpcsjax.optimization.nlsq.heterodyne_stratified_ls as hsl

    model, c2, phi = _make_synthetic_heterodyne()
    _install_model_stub(monkeypatch, model)

    called = {"strat": False}

    def _fake_strat(**k):
        called["strat"] = True
        return object()

    monkeypatch.setattr(hsl, "fit_heterodyne_stratified_least_squares", _fake_strat)
    # Force the gate above 1M without allocating a huge array.
    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq._estimate_heterodyne_points",
        lambda c2, phi: 2_000_000,
    )
    # The engine route runs no global escape; it is already gated off by
    # ``multistart_on`` — guard it so a regression surfaces here too.
    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.heterodyne_engine_route.fit_two_component_via_engine",
        lambda *a, **k: (_ for _ in ()).throw(
            AssertionError("engine route must not run when flat multistart is on")
        ),
    )
    import numpy as _np

    class _R:
        parameters = _np.zeros(1)
        chi_squared = 0.0
        reduced_chi_squared = 0.0
        success = True
        message = "ok"
        nlsq_diagnostics: dict = {}

    joint = {}
    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.heterodyne_core.fit_nlsq_multi_phi",
        lambda *a, **k: joint.setdefault("yes", True) or _R(),
    )
    cfg = _Cfg(
        {
            "analysis_mode": "two_component",
            "optimization": {"nlsq": {"multistart": True}},
        }
    )
    data = {"c2_exp": c2, "phi_angles_list": phi}
    nlsq_pkg.fit_nlsq(data, cfg)
    assert called["strat"] is False, (
        "Stratified-LS solver was called despite flat multistart=true "
        "(multistart escape is owned by fit_nlsq_multi_phi)"
    )
    assert joint.get("yes") is True  # routed to fit_nlsq_multi_phi (owns the escape)


def test_pointwise_data_excludes_t0_and_diagonal():
    """Pointwise training data must match the meshgrid residual support:
    no diagonal, no t=0 row/col -> (n_t-1)*(n_t-2) points per angle."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        build_heterodyne_pointwise_model,
    )

    n_phi, n_t = 2, 8
    model, c2, phi = _make_synthetic_heterodyne(n_phi=n_phi, n_t=n_t)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    _fn, x_data, y_data, _p0, meta = build_heterodyne_pointwise_model(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
    )
    t1 = x_data[:, 1]
    t2 = x_data[:, 2]
    assert not (t1 == t2).any(), "diagonal not excluded"
    assert (t1 > 0).all() and (t2 > 0).all(), "t=0 boundary not excluded"
    assert x_data.shape[0] == n_phi * (n_t - 1) * (n_t - 2)
    assert y_data.shape[0] == x_data.shape[0]
    assert meta["n_data_points"] == x_data.shape[0]


def test_initial_params_override_is_honored(monkeypatch):
    import xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming as hs
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )

    seen = {}

    class _FakeOpt:
        def __init__(self, config):
            pass

        def fit(self, data_source, func, p0, bounds=None, sigma=None, **kw):
            seen["p0"] = np.asarray(p0).copy()
            n = len(p0)
            return {"x": np.zeros(n), "pcov": np.eye(n), "nit": 1, "success": True}

    monkeypatch.setattr(hs, "AdaptiveHybridStreamingOptimizer", _FakeOpt)
    model, c2, phi = _make_synthetic_heterodyne()
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    n = model.param_manager.n_varying
    custom = np.arange(1, n + 1, dtype=np.float64) * 1.5
    hs.fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=custom,
        bounds=None,
        hybrid_config={"enable": True},
        # Pin constant so p0 stays physics-only (this test checks the
        # initial_params override, not the scaling mode). Default is now 'auto'.
        anti_degeneracy_config={"per_angle_mode": "constant"},
    )
    assert np.allclose(seen["p0"], custom), "initial_params override ignored"


def test_reduced_chi_squared_uses_data_dof():
    from xpcsjax.optimization.nlsq.heterodyne_result_builder import build_hybrid_streaming_result

    model, c2, phi = _make_synthetic_heterodyne()
    n = model.param_manager.n_varying
    res = build_hybrid_streaming_result(
        model=model,
        popt=np.zeros(n),
        pcov=np.eye(n),
        info={
            "nit": 1,
            "success": True,
            "n_data_points": 100_000,
            "hybrid_streaming_diagnostics": {},
        },
        phi_angles=phi,
    )
    # dof must reflect n_data - n_params (~100k), not n_params (~14). With chi2 ~ O(n_data),
    # reduced should not be astronomically inflated. Just assert it's finite and the result is built.
    assert (
        np.isfinite(res.reduced_chi_squared) or res.reduced_chi_squared != res.reduced_chi_squared
    )  # finite or NaN ok


def test_pointwise_model_averaged_param_layout():
    """averaged prepends 2 optimized scaling params (scaling-first head); model_fn
    reads them."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        build_heterodyne_pointwise_model,
    )

    # _make_synthetic_heterodyne returns (model, c2, phi)
    model, c2, phi = _make_synthetic_heterodyne()
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)

    model_fn, x_data, y_data, p0, meta = build_heterodyne_pointwise_model(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        per_angle_mode="averaged",
    )
    n_phys = len(model.param_manager.get_initial_values())
    assert len(p0) == n_phys + 2
    # Scaling-first head: contrast at p0[0], offset at p0[1].
    assert np.isclose(p0[0], float(np.mean(meta["contrast_arr"])))
    assert np.isclose(p0[1], float(np.mean(meta["offset_arr"])))
    pred = np.asarray(model_fn(x_data[:8], *[float(v) for v in p0]))
    assert pred.shape == (8,)
    assert np.all(np.isfinite(pred))
    assert meta["per_angle_mode"] == "averaged"
    assert meta["n_scaling"] == 2
    assert meta["n_physics_varying"] == n_phys
    scaling_lower, scaling_upper = meta["scaling_bounds"]
    assert scaling_lower.dtype == np.float64
    assert scaling_upper.dtype == np.float64
    assert len(scaling_lower) == 2
    assert len(scaling_upper) == 2
    assert scaling_lower[0] == 0.01
    assert np.isclose(scaling_upper[0], max(2.0 * p0[0], 1.0))


def test_streaming_averaged_optimizes_scaling_and_sets_group_variance(monkeypatch):
    """Task 2 (structural): anti_degeneracy_config consumed; averaged resolves;
    group-variance config injected with the correct indices.

    Uses a MOCK optimizer that returns p0 unchanged, so this test asserts ONLY
    the structural / config contract (param layout, mode, spliced bounds, and the
    HybridStreamingConfig group-variance fields). The SSR-improvement claim is
    verified separately by test_streaming_auto_averaged_real_run_ssr_not_worse,
    because with a no-op optimizer popt == p0 and SSR parity is vacuous.

    Also covers issue #20 (heterodyne streaming's OWN L3
    ``AdaptiveRegularizationConfig`` call site -- heterodyne_hybrid_streaming.py
    line ~630, inside this same function -- was untested; the sibling laminar
    site is covered by test_hybrid_streaming_auto_tune_lambda.py). The spy
    patches the source module (xpcsjax.optimization.nlsq.adaptive_regularization)
    rather than the ``hs`` module namespace because the call site imports
    ``AdaptiveRegularizationConfig`` function-locally, at call time.
    """
    import xpcsjax.optimization.nlsq.adaptive_regularization as adaptive_reg
    import xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming as hs
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )

    captured = {}
    reg_captured = {}
    real_reg_config = adaptive_reg.AdaptiveRegularizationConfig

    def _spy_reg_config(**kwargs):
        reg_captured["kwargs"] = kwargs
        return real_reg_config(**kwargs)

    monkeypatch.setattr(adaptive_reg, "AdaptiveRegularizationConfig", _spy_reg_config)

    class _FakeOpt:
        def __init__(self, config):
            captured["config"] = config

        def fit(self, data_source, func, p0, bounds=None, sigma=None, **kw):
            captured["p0_len"] = len(p0)
            captured["bounds"] = bounds
            n = len(p0)
            # Return p0 unchanged — a no-op (structural-contract) fit
            return {
                "x": np.asarray(p0, dtype=np.float64),
                "pcov": np.eye(n),
                "nit": 3,
                "success": True,
            }

    monkeypatch.setattr(hs, "AdaptiveHybridStreamingOptimizer", _FakeOpt)

    # n_phi=3 — exercises the multi-angle path
    model, c2, phi = _make_synthetic_heterodyne(n_phi=3, n_t=6)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)

    n_phys = model.param_manager.n_varying
    lower_phys, upper_phys = model.param_manager.get_bounds()
    p0_phys = np.asarray(model.param_manager.get_initial_values(), dtype=np.float64)
    bounds = (np.asarray(lower_phys, dtype=np.float64), np.asarray(upper_phys, dtype=np.float64))

    popt, pcov, info = hs.fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=p0_phys,
        bounds=bounds,
        anti_degeneracy_config={"per_angle_mode": "auto"},
    )

    # popt has 2 extra scaling params prepended (scaling-first head)
    assert len(popt) == n_phys + 2, f"Expected {n_phys + 2} params, got {len(popt)}"
    assert info["anti_degeneracy"]["per_angle_mode"] == "averaged"
    # bounds were spliced to include scaling tail
    assert captured["bounds"] is not None
    assert len(captured["bounds"][0]) == n_phys + 2
    assert len(captured["bounds"][1]) == n_phys + 2
    # HybridStreamingConfig must carry the group-variance regularization fields
    cfg = captured["config"]
    assert cfg.enable_group_variance_regularization is True
    assert cfg.group_variance_lambda > 0.0
    # Scaling-first: the scaling head is at full-vector indices [0, n_scaling),
    # so the group indices are head-local.
    assert cfg.group_variance_indices == [(0, 1), (1, 2)]
    # Issue #20: no `regularization` key configured -> auto_tune_lambda must
    # default to True at this streaming call site (not just at the
    # AntiDegeneracyConfig.from_dict parsing layer).
    assert "kwargs" in reg_captured, "AdaptiveRegularizationConfig must have been constructed"
    assert reg_captured["kwargs"]["auto_tune_lambda"] is True

    # Issue #20: an explicit auto_tune_lambda=False must reach the same call site.
    reg_captured.clear()
    hs.fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=p0_phys,
        bounds=bounds,
        anti_degeneracy_config={
            "per_angle_mode": "auto",
            "regularization": {"auto_tune_lambda": False},
        },
    )
    assert "kwargs" in reg_captured, "AdaptiveRegularizationConfig must have been constructed"
    assert reg_captured["kwargs"]["auto_tune_lambda"] is False, (
        "regularization.auto_tune_lambda=False must reach the heterodyne streaming "
        "path's own AdaptiveRegularizationConfig (heterodyne_hybrid_streaming.py "
        f"line ~630); got {reg_captured['kwargs']['auto_tune_lambda']!r}."
    )


def test_streaming_auto_threshold_routing():
    """Mirror laminar's auto dispatch: sub-threshold `auto` (n_phi <
    constant_scaling_threshold) routes to `individual` (per-angle scaling, which
    activates the L2 hierarchical branch); at/above the threshold it resolves to
    `averaged` (L2 off). n_phi=2 vs the default threshold 3."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne as fit_fn,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=2, n_t=6)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()
    common = dict(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={
            "warmup_iterations": 5,
            "max_warmup_iterations": 10,
            "gauss_newton_max_iterations": 5,
            "verbose": 0,
        },
    )
    # n_phi=2 < default threshold 3 -> individual (activates L2 hierarchical)
    info_ind = fit_fn(**common, anti_degeneracy_config={"per_angle_mode": "auto"})[2]
    assert info_ind["anti_degeneracy"]["per_angle_mode"] == "individual"
    assert info_ind["anti_degeneracy"]["hierarchical_active"] is True
    # Lowering the threshold to 2 makes n_phi=2 resolve to averaged (L2 off)
    info_avg = fit_fn(
        **common,
        anti_degeneracy_config={"per_angle_mode": "auto", "constant_scaling_threshold": 2},
    )[2]
    assert info_avg["anti_degeneracy"]["per_angle_mode"] == "averaged"
    assert info_avg["anti_degeneracy"]["hierarchical_active"] is False


def test_streaming_l4_monitor_present_and_objective_invariant():
    """Task 3: L4 gradient-collapse monitor diagnostics appear in anti_degeneracy;
    monitor-on vs monitor-off must be objective-identical (strictly observational)."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=2, n_t=8)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()

    base_kwargs = dict(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={
            "warmup_iterations": 10,
            "max_warmup_iterations": 20,
            "gauss_newton_max_iterations": 10,
            "verbose": 0,
        },
    )

    # Monitor ON
    _, _, info_on = fit_with_stratified_hybrid_streaming_heterodyne(
        **base_kwargs,
        anti_degeneracy_config={"per_angle_mode": "auto", "gradient_monitoring": {"enable": True}},
    )
    # Monitor OFF
    _, _, info_off = fit_with_stratified_hybrid_streaming_heterodyne(
        **base_kwargs,
        anti_degeneracy_config={"per_angle_mode": "auto", "gradient_monitoring": {"enable": False}},
    )

    # gradient_monitor key must be present when monitoring is on
    assert "gradient_monitor" in info_on["anti_degeneracy"], (
        f"gradient_monitor missing from anti_degeneracy; keys={list(info_on['anti_degeneracy'].keys())}"
    )
    # Monitor must be strictly observational: SSR must be identical regardless of monitoring
    assert np.isclose(info_on["ssr"], info_off["ssr"], rtol=0, atol=1e-9), (
        f"Monitor changed objective: on={info_on['ssr']:.10e}  off={info_off['ssr']:.10e}"
    )


def test_streaming_averaged_real_run_ssr_not_worse():
    """Fix 3: REAL optimizer run (no mock). Optimizing the averaged scaling tail
    must do at least as well as the frozen-quantile baseline (shared physics).

    Kept tiny (n_phi=2, n_t=8, few iterations) so it runs in a few seconds.
    Uses finite physics bounds — the path heterodyne_core actually takes (nlsq's
    hybrid-streaming optimizer corrupts ±inf bounds to NaN, see Fix 2)."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=2, n_t=8)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()

    popt, pcov, info = fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={
            "warmup_iterations": 10,
            "max_warmup_iterations": 20,
            "gauss_newton_max_iterations": 10,
            "verbose": 0,
        },
        # threshold=2 pins auto->averaged at n_phi=2 (this test targets the
        # averaged path; sub-threshold auto->individual is covered separately).
        anti_degeneracy_config={"per_angle_mode": "auto", "constant_scaling_threshold": 2},
    )

    assert info["anti_degeneracy"]["per_angle_mode"] == "averaged"
    assert np.isfinite(info["ssr"])
    assert np.isfinite(info["ssr_frozen_baseline"])
    # Optimizing the scaling tail (shared fitted physics) must beat-or-tie the
    # frozen-quantile default.
    assert info["ssr"] <= info["ssr_frozen_baseline"] + 1e-9, (
        f"ssr={info['ssr']:.6e} > ssr_frozen_baseline={info['ssr_frozen_baseline']:.6e}"
    )


# ---------------------------------------------------------------------------
# individual scaling-head expansion (scaling-first)
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("mode", ["individual"])
def test_pointwise_model_individual_layout(mode):
    """individual per_angle_mode: correct scaling-head layout, p0 length,
    meta fields, and a finite forward pass."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        build_heterodyne_pointwise_model,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=6, n_t=8)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)

    model_fn, x_data, y_data, p0, meta = build_heterodyne_pointwise_model(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        per_angle_mode=mode,
    )

    n_phys = len(model.param_manager.get_initial_values())
    n_phi = len(meta["phi_unique"])

    assert meta["n_scaling"] == 2 * n_phi, (
        f"individual: expected n_scaling=2*{n_phi}={2 * n_phi}, got {meta['n_scaling']}"
    )

    assert len(p0) == n_phys + meta["n_scaling"], (
        f"p0 length mismatch: {len(p0)} vs {n_phys} + {meta['n_scaling']}"
    )

    # Check meta fields are populated
    assert meta["per_angle_mode"] == mode
    assert meta["n_phi"] == n_phi
    assert meta["n_physics_varying"] == n_phys
    scaling_lower, scaling_upper = meta["scaling_bounds"]
    assert len(scaling_lower) == meta["n_scaling"]
    assert len(scaling_upper) == meta["n_scaling"]
    assert scaling_lower.dtype == np.float64
    assert scaling_upper.dtype == np.float64
    # All bounds must be finite
    assert np.all(np.isfinite(scaling_lower)), "scaling_lower has non-finite values"
    assert np.all(np.isfinite(scaling_upper)), "scaling_upper has non-finite values"
    assert np.all(scaling_lower < scaling_upper), "scaling bounds not lower < upper"

    # Forward pass must return finite values
    pred = np.asarray(model_fn(x_data[:8], *[float(v) for v in p0]))
    assert pred.shape == (8,), f"pred shape {pred.shape}"
    assert np.all(np.isfinite(pred)), f"pred has non-finite: {pred}"


# ---------------------------------------------------------------------------
# L2 hierarchical branch for individual
# ---------------------------------------------------------------------------


def test_streaming_l2_gate_and_activation():
    """L2 hierarchical runs for individual (not use_constant), off for averaged.

    Uses a real (but tiny) optimizer run so hierarchical_active is determined by
    the actual code path, not a mock.  n_phi=4 makes individual meaningful (4
    per-angle contrast + 4 per-angle offset params).

    The dataset is deliberately small so the hierarchical loss_fn's full-vector
    materialisation is cheap (see implementation comment: L2 only fires for
    individual, which auto selects at small n_phi).
    """
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=4, n_t=6)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()
    base_kwargs = dict(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={
            "warmup_iterations": 5,
            "max_warmup_iterations": 10,
            "gauss_newton_max_iterations": 5,
            "verbose": 0,
        },
    )

    # individual -> L2 must be active
    _, _, info_ind = fit_with_stratified_hybrid_streaming_heterodyne(
        **base_kwargs,
        anti_degeneracy_config={
            "per_angle_mode": "individual",
            "hierarchical": {"enable": True, "max_outer_iterations": 2},
        },
    )
    assert info_ind["anti_degeneracy"]["hierarchical_active"] is True, (
        f"individual: expected hierarchical_active=True, got "
        f"{info_ind['anti_degeneracy']['hierarchical_active']}"
    )

    # auto (-> averaged) -> L2 must be off
    _, _, info_avg = fit_with_stratified_hybrid_streaming_heterodyne(
        **base_kwargs,
        anti_degeneracy_config={"per_angle_mode": "auto"},
    )
    assert info_avg["anti_degeneracy"]["hierarchical_active"] is False, (
        f"averaged: expected hierarchical_active=False, got "
        f"{info_avg['anti_degeneracy']['hierarchical_active']}"
    )


def test_streaming_l2_diagnostics_keys_present_for_individual():
    """When L2 fires (individual mode) the anti_degeneracy block must still
    carry all symmetric keys required by the diagnostics contract."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=4, n_t=6)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()

    _, _, info = fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={
            "warmup_iterations": 5,
            "max_warmup_iterations": 10,
            "gauss_newton_max_iterations": 5,
            "verbose": 0,
        },
        anti_degeneracy_config={
            "per_angle_mode": "individual",
            "hierarchical": {"enable": True, "max_outer_iterations": 2},
        },
    )
    ad = info["anti_degeneracy"]
    for k in ("hierarchical_active", "regularization_active", "shear_weighting", "per_angle_mode"):
        assert k in ad, f"missing key {k!r} in anti_degeneracy"
    assert ad["hierarchical_active"] is True
    assert ad["per_angle_mode"] == "individual"
    assert ad["shear_weighting"] == "laminar_flow_inactive"
    assert np.isfinite(info["ssr"])


def test_streaming_l2_ssr_finite_for_individual():
    """Hierarchical path must produce finite SSR and correct popt length."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=4, n_t=6)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()
    n_phys = model.param_manager.n_varying

    popt, pcov, info = fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={
            "warmup_iterations": 5,
            "max_warmup_iterations": 10,
            "gauss_newton_max_iterations": 5,
            "verbose": 0,
        },
        anti_degeneracy_config={
            "per_angle_mode": "individual",
            "hierarchical": {"enable": True, "max_outer_iterations": 2},
        },
    )
    # n_phys + 2*n_phi scaling params
    assert len(popt) == n_phys + 2 * 4, f"popt length {len(popt)} != {n_phys + 8}"
    assert np.all(np.isfinite(popt)), "popt has non-finite values"
    assert np.isfinite(info["ssr"]), f"SSR not finite: {info['ssr']}"


def test_streaming_l2_real_data_non_psd_hessian_falls_back_to_placeholder(caplog):
    """A genuine bounded-L2 solve whose Hessian is NOT positive-definite must fall
    back to the honest identity placeholder, not a misleading covariance.

    L2 uses bounded L-BFGS-B, so a solution resting on a bound is not an interior
    stationary point and its unconstrained Hessian need not be positive-definite.
    Empirically (verified during three-brain and PR review) this fixture's Hessian
    is degenerate at every size tried (n_t = 6, 12, 16 -- bigger fixtures made it
    worse, not better; at n_phi=4, n_t=6 the un-noised Hessian is rank 11/22),
    which is exactly the kind of boundary-constrained solve this codebase's own
    5-layer anti-degeneracy design anticipates.

    WHICH of the two non-PSD failure modes fires on this exact fixture is
    genuinely platform/BLAS-dependent, confirmed by CI: on the maintainer's dev
    machine `np.linalg.inv` raises `LinAlgError` (Hessian numerically singular);
    on GitHub's ubuntu-latest/py3.14 runner (different XLA:CPU/BLAS backend --
    see CLAUDE.md's documented precedent for this exact class of platform
    fragility) `inv` succeeds but returns a negative-diagonal covariance instead.
    Both are non-PSD Hessians from the same underlying degeneracy and both
    correctly route to the identity placeholder -- see the block comment above
    the covariance computation in `heterodyne_hybrid_streaming.py` for the full
    rationale on both guards. This test asserts the OUTCOME (placeholder fires,
    for one of these two specific reasons) rather than committing to exactly
    which numerical path a non-convex boundary solve happens to take on a given
    host. The deterministic complement that proves the SUCCESS path is
    ``test_streaming_l2_real_hessian_covariance_via_inv_on_success``; the
    deterministic complements that prove each mechanism individually (mocked
    Hessians, not real physics data, so platform-independent) are
    ``test_streaming_l2_singular_hessian_falls_back_to_placeholder`` and
    ``test_streaming_l2_hessian_failure_falls_back_to_placeholder``.
    """
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne,
    )

    # _make_synthetic_heterodyne generates c2 EXACTLY at the model's initial
    # parameters (residual ~= 0 by construction). Left un-noised, this collapses
    # s2 to 0 -- pcov would be all-zero regardless of H's rank, which would still
    # satisfy "finite"/"not eye" checks in a success-oriented test but proves
    # nothing here either. Inject noise so s2 > 0 and the genuinely rank-deficient
    # Hessian (confirmed at every size tried) reaches one of the non-PSD guard
    # branches rather than being masked by a degenerate s2=0 scale factor.
    model, c2, phi = _make_synthetic_heterodyne(n_phi=4, n_t=6)
    rng = np.random.default_rng(seed=20260821)
    c2_noisy = c2 + rng.normal(0.0, 1e-3, size=c2.shape)

    strat = build_heterodyne_stratified_data(model, c2_noisy, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()

    with caplog.at_level(
        "ERROR",
        logger="xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming",
    ):
        popt, pcov, info = fit_with_stratified_hybrid_streaming_heterodyne(
            stratified_data=strat,
            model=model,
            physical_param_names=list(model.param_manager.varying_names),
            initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
            bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
            hybrid_config={
                "warmup_iterations": 5,
                "max_warmup_iterations": 10,
                "gauss_newton_max_iterations": 5,
                "verbose": 0,
            },
            anti_degeneracy_config={
                "per_angle_mode": "individual",
                "hierarchical": {"enable": True, "max_outer_iterations": 2},
                # NOTE (implementer finding, verified 2026-08-22): L3's default
                # regularization mode is "relative" (CV-based, uses jnp.std). The
                # quantile-based per-angle init seeds every angle with the SAME
                # contrast/offset (all angles are statistically identical in this
                # synthetic fixture), so each group's std is exactly 0 at init and
                # stays there through the 2-outer-iteration L2 fit (Stage 2 barely
                # perturbs it). jnp.std has an unconditional NaN gradient/Hessian
                # at zero variance (`jax.hessian(jnp.std)([.5]*4)` == all-NaN,
                # verified directly) -- a pre-existing bug in
                # xpcsjax/optimization/nlsq/adaptive_regularization.py's CV branch
                # that is OUT OF SCOPE for this task (only heterodyne_hybrid_streaming.py
                # and this test file are in scope). Forcing "auto" mode here (which
                # takes the jnp.var branch instead of jnp.std for n_phi=4 <= 5)
                # keeps this test on the failure mode it is meant to prove -- var is
                # polynomial in the params and has a well-defined Hessian everywhere,
                # including at zero variance, so the covariance block reaches the PSD
                # guard rather than dying on the unrelated L3 NaN singularity. Do NOT
                # remove this override: without it the assertions below would pass for
                # the WRONG reason.
                "regularization": {"mode": "auto"},
            },
        )

    n = popt.shape[0]
    assert pcov.shape == (n, n)
    assert np.all(np.isfinite(pcov))
    assert np.array_equal(pcov, np.eye(n))
    assert info["covariance_is_placeholder"] is True
    assert info["hybrid_streaming_diagnostics"]["covariance_is_placeholder"] is True, (
        "nested diagnostics block must mirror the top-level flag"
    )
    # Pin WHICH FAMILY of failure fired: either non-PSD guard (singular Hessian,
    # or a successful-but-negative-diagonal inv() -- both legitimate outcomes of
    # this same degeneracy, platform-dependent per the docstring above), but NOT
    # a non-finite Hessian or the out-of-scope L3 NaN singularity. Without this,
    # a future L3 regression would silently turn this into a test of the wrong
    # failure mode.
    msg = " ".join(r.getMessage().lower() for r in caplog.records if r.levelname == "ERROR")
    assert "singular" in msg or "negative diagonal" in msg, (
        "expected a non-PSD-Hessian guard (singular or negative-diagonal) to be "
        "the failure that fired, not something else"
    )


def test_streaming_l2_real_hessian_covariance_via_inv_on_success(monkeypatch, caplog):
    """A well-conditioned (SPD) Hessian must take the real ``np.linalg.inv`` path and
    report a genuine, non-placeholder covariance.

    Deterministic complement to
    ``test_streaming_l2_real_data_non_psd_hessian_falls_back_to_placeholder``,
    which proves the PSD guard fires correctly on the codebase's own real degenerate
    solves. This test proves the SUCCESS path itself is correct when the Hessian
    genuinely IS positive-definite, without depending on a real fit happening to land
    there -- reverse-engineering a genuinely well-conditioned real fixture is
    nontrivial (three sizes were tried and all were degenerate), so the Hessian is
    mocked, exactly as the neighbouring failure / pinv tests do.
    """
    import jax.numpy as jnp

    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies import (
        heterodyne_hybrid_streaming as hs,
    )

    def _well_conditioned_hessian(fn):
        def _spd_hessian(p):
            n = p.shape[0]
            return jnp.eye(n) * 4.0  # arbitrary well-conditioned SPD matrix

        return _spd_hessian

    monkeypatch.setattr(hs.jax, "hessian", _well_conditioned_hessian)

    # Noise is load-bearing: the fixture generates c2 exactly at the initial
    # params, so an un-noised fit gives hier_result.fun ~= 0 -> s2 ~= 0 ->
    # pcov = 2*s2*inv(4I) = all-zeros. That would still satisfy "finite",
    # "not eye", and "placeholder is False" while proving nothing, so inject
    # noise to keep s2 strictly positive.
    model, c2, phi = _make_synthetic_heterodyne(n_phi=4, n_t=6)
    rng = np.random.default_rng(seed=20260822)
    c2_noisy = c2 + rng.normal(0.0, 1e-3, size=c2.shape)

    strat = build_heterodyne_stratified_data(model, c2_noisy, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()

    with caplog.at_level(
        "WARNING",
        logger="xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming",
    ):
        popt, pcov, info = hs.fit_with_stratified_hybrid_streaming_heterodyne(
            stratified_data=strat,
            model=model,
            physical_param_names=list(model.param_manager.varying_names),
            initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
            bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
            hybrid_config={
                "warmup_iterations": 5,
                "max_warmup_iterations": 10,
                "gauss_newton_max_iterations": 5,
                "verbose": 0,
            },
            anti_degeneracy_config={
                "per_angle_mode": "individual",
                "hierarchical": {"enable": True, "max_outer_iterations": 2},
            },
        )

    n = popt.shape[0]
    assert pcov.shape == (n, n)
    assert np.all(np.isfinite(pcov))
    assert np.all(np.diag(pcov) > 0), "SPD Hessian must yield strictly positive variances"
    assert not np.array_equal(pcov, np.eye(n))
    assert info["covariance_is_placeholder"] is False
    assert info["hybrid_streaming_diagnostics"]["covariance_is_placeholder"] is False, (
        "nested diagnostics block must mirror the top-level flag"
    )
    # pinv(4I) == inv(4I) numerically, so an isotropic mock cannot distinguish
    # the two branches by comparing pcov's shape/positivity/eye-ness alone --
    # a dropped 2.0 factor, a wrong s2, or H.T instead of H would all still
    # satisfy those checks. Compute the exact expected covariance from the
    # formula this branch is supposed to implement (2 * s2 * inv(H)) using
    # only publicly returned fields, and compare element-wise.
    n_hier_data = int(info["n_data_points"])
    final_cost = float(
        info["hybrid_streaming_diagnostics"]["gauss_newton_diagnostics"]["final_cost"]
    )
    s2_hier = final_cost / max(n_hier_data - n, 1)
    H_mock = np.eye(n) * 4.0
    expected_pcov = 2.0 * s2_hier * np.linalg.inv(H_mock)
    np.testing.assert_allclose(
        pcov,
        expected_pcov,
        rtol=1e-10,
        err_msg="pcov does not match 2*s2*inv(H) for the known mocked H -- "
        "formula/scale-factor regression",
    )
    # The exact-formula check above already proves inv() (not pinv) ran --
    # pinv(4I) == inv(4I) so this would pass either way on VALUES alone, but a
    # WARNING log is unique to the pinv branch, so its absence is independent
    # confirmation of which branch actually executed.
    assert not any("Singular Hessian" in r.getMessage() for r in caplog.records), (
        "expected the real np.linalg.inv path, but the pinv fallback fired"
    )


def test_streaming_l2_hessian_failure_falls_back_to_placeholder(monkeypatch, caplog):
    """If jax.hessian raises, the L2 branch must fall back to the identity
    placeholder, set covariance_is_placeholder=True, and log an ERROR
    explaining the reported uncertainties are not meaningful."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies import (
        heterodyne_hybrid_streaming as hs,
    )

    def _raise_hessian(fn):
        raise RuntimeError("forced hessian failure for test")

    monkeypatch.setattr(hs.jax, "hessian", _raise_hessian)

    model, c2, phi = _make_synthetic_heterodyne(n_phi=4, n_t=6)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()

    with caplog.at_level(
        "ERROR",
        logger="xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming",
    ):
        popt, pcov, info = hs.fit_with_stratified_hybrid_streaming_heterodyne(
            stratified_data=strat,
            model=model,
            physical_param_names=list(model.param_manager.varying_names),
            initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
            bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
            hybrid_config={
                "warmup_iterations": 5,
                "max_warmup_iterations": 10,
                "gauss_newton_max_iterations": 5,
                "verbose": 0,
            },
            anti_degeneracy_config={
                "per_angle_mode": "individual",
                "hierarchical": {"enable": True, "max_outer_iterations": 2},
            },
        )

    n = popt.shape[0]
    assert np.array_equal(pcov, np.eye(n))
    assert info["covariance_is_placeholder"] is True
    assert info["hybrid_streaming_diagnostics"]["covariance_is_placeholder"] is True, (
        "nested diagnostics block must mirror the top-level flag"
    )
    assert any(
        "identity placeholder" in r.getMessage() and r.levelname == "ERROR" for r in caplog.records
    ), "expected an ERROR log explaining the covariance is a placeholder"


def test_streaming_l2_singular_hessian_falls_back_to_placeholder(monkeypatch, caplog):
    """A singular Hessian must fall back to the identity placeholder, NOT a
    pseudo-inverse.

    Deliberately diverges from laminar's origin (which recovers via
    ``np.linalg.pinv`` and stays non-placeholder): ``pinv``'s Moore-Penrose
    null-space treatment reports the unidentified direction's variance as
    EXACTLY 0.0 (infinite precision) rather than the statistically correct
    answer (unbounded uncertainty, since a singular Hessian means that
    direction is genuinely unconstrained by the fit) -- a confidently-wrong
    "known" that the PSD guard's `< 0` check cannot catch, since 0.0 is not
    negative. See the block comment above the covariance computation in
    ``heterodyne_hybrid_streaming.py`` for the full rationale.
    """
    import jax.numpy as jnp

    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies import (
        heterodyne_hybrid_streaming as hs,
    )

    def _singular_hessian(fn):
        def _zero_hessian(p):
            n = p.shape[0]
            return jnp.zeros((n, n))

        return _zero_hessian

    monkeypatch.setattr(hs.jax, "hessian", _singular_hessian)

    model, c2, phi = _make_synthetic_heterodyne(n_phi=4, n_t=6)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()

    with caplog.at_level(
        "ERROR",
        logger="xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming",
    ):
        popt, pcov, info = hs.fit_with_stratified_hybrid_streaming_heterodyne(
            stratified_data=strat,
            model=model,
            physical_param_names=list(model.param_manager.varying_names),
            initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
            bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
            hybrid_config={
                "warmup_iterations": 5,
                "max_warmup_iterations": 10,
                "gauss_newton_max_iterations": 5,
                "verbose": 0,
            },
            anti_degeneracy_config={
                "per_angle_mode": "individual",
                "hierarchical": {"enable": True, "max_outer_iterations": 2},
            },
        )

    n = popt.shape[0]
    assert pcov.shape == (n, n)
    assert np.array_equal(pcov, np.eye(n))
    assert info["covariance_is_placeholder"] is True
    assert info["hybrid_streaming_diagnostics"]["covariance_is_placeholder"] is True, (
        "nested diagnostics block must mirror the top-level flag"
    )
    assert any(
        "singular" in r.getMessage().lower() and r.levelname == "ERROR" for r in caplog.records
    ), "expected the ERROR log to name the singular-Hessian failure specifically"


def test_streaming_diagnostics_symmetric_keys():
    """Streaming anti_degeneracy block carries the same top-level keys as other paths."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=2, n_t=8)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()

    _, _, info = fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={
            "warmup_iterations": 10,
            "max_warmup_iterations": 20,
            "gauss_newton_max_iterations": 10,
            "verbose": 0,
        },
        # threshold=2 pins auto->averaged at n_phi=2 (this test asserts the
        # averaged contract: hierarchical_active False).
        anti_degeneracy_config={
            "per_angle_mode": "auto",
            "constant_scaling_threshold": 2,
            "gradient_monitoring": {"enable": True},
        },
    )

    ad = info["anti_degeneracy"]
    for k in ("hierarchical_active", "regularization_active", "shear_weighting", "per_angle_mode"):
        assert k in ad, f"missing {k}"
    # gradient_monitor is emitted only when L4 ran; this test enables it, so it must be present here
    assert "gradient_monitor" in ad
    assert ad["shear_weighting"] == "laminar_flow_inactive"
    assert ad["hierarchical_active"] is False  # averaged => L2 off


# ---------------------------------------------------------------------------
# constant frozen-scaling regression guard + None-config default
# ---------------------------------------------------------------------------


def test_streaming_constant_matches_legacy_frozen_scaling():
    """Explicit constant mode reproduces today's frozen-scaling streaming result.

    per_angle_mode='constant' resolves to the canonical 'constant': scaling is
    frozen inside the JIT closure (quantile estimates are NOT optimized).  popt is
    physics-only (len == n_varying).
    """
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=2, n_t=8)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()
    p0 = np.asarray(model.param_manager.get_initial_values(), dtype=np.float64)
    n_phys = len(p0)

    popt, _pcov, info = fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=p0,
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={
            "warmup_iterations": 10,
            "max_warmup_iterations": 20,
            "gauss_newton_max_iterations": 10,
            "verbose": 0,
        },
        anti_degeneracy_config={"per_angle_mode": "constant"},
    )

    # No scaling head: physics-only vector (frozen-scaling behavior)
    assert len(popt) == n_phys, (
        f"constant: expected len(popt)={n_phys} (physics-only), got {len(popt)}"
    )
    assert info["anti_degeneracy"]["per_angle_mode"] == "constant", (
        f"per_angle_mode={info['anti_degeneracy']['per_angle_mode']!r}, expected 'constant'"
    )
    assert info["anti_degeneracy"]["hierarchical_active"] is False, (
        "constant must not activate L2 hierarchical"
    )
    # SSR must be finite
    assert np.isfinite(info["ssr"]), f"ssr not finite: {info['ssr']}"


def test_streaming_none_config_defaults_to_auto():
    """No/None anti_degeneracy_config defaults to 'auto' — mirroring laminar
    (hybrid_streaming.py:550), which has no "freeze when unconfigured" special
    case. It does NOT freeze scaling. At n_phi=2 (< threshold 3) 'auto' resolves
    to 'individual' (per-angle optimized scaling + L2 hierarchical), so popt
    carries the 2*n_phi scaling head. Frozen 'constant' scaling is reachable only
    via the explicit opt-out per_angle_mode='constant' (covered separately).
    """
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=2, n_t=8)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()
    p0 = np.asarray(model.param_manager.get_initial_values(), dtype=np.float64)
    n_phys = len(p0)
    n_phi = len(set(phi.tolist()))

    popt, _pcov, info = fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=p0,
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={
            "warmup_iterations": 5,
            "max_warmup_iterations": 10,
            "gauss_newton_max_iterations": 5,
            "verbose": 0,
        },
        anti_degeneracy_config=None,
    )

    # None config -> 'auto' -> (n_phi=2 < 3) -> 'individual' (optimizes scaling).
    ad = info["anti_degeneracy"]
    assert ad["per_angle_mode"] == "individual", (
        f"None config: per_angle_mode={ad['per_angle_mode']!r}, expected 'individual' "
        "(auto default, NOT frozen constant)"
    )
    assert ad["hierarchical_active"] is True
    assert len(popt) == n_phys + 2 * n_phi, (
        f"expected scaling tail: len(popt)={n_phys + 2 * n_phi}, got {len(popt)}"
    )


def test_streaming_l2_individual_ssr_not_worse():
    """REAL hierarchical (L2) run for per_angle_mode='individual'. Optimizing the
    per-angle scaling tail (jointly with shared physics, via hierarchical
    alternation) cannot worsen the data objective relative to the frozen
    per-angle quantile baseline.

    This guards the hierarchical path after the Task-6 spec-review fixes:
      - Bug 1: L3 AdaptiveRegularizer now slices the scaling tail (full-vector
        indices), not the physics head. A wrong-slice regularizer would penalise
        the physics params and could push SSR above the frozen baseline.
      - Bug 2: L4 monitor now receives native-layout gradient/params (diagnostic
        only; does not affect SSR but is exercised here on the real path).

    n_phi=4 makes 'individual' meaningful (4 per-angle contrast + 4 offset
    params). Kept tiny (n_t=6, few iterations) so it runs in a few seconds.
    """
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=4, n_t=6)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()

    _, _, info = fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={
            "warmup_iterations": 5,
            "max_warmup_iterations": 10,
            "gauss_newton_max_iterations": 5,
            "verbose": 0,
        },
        anti_degeneracy_config={
            "per_angle_mode": "individual",
            "hierarchical": {"enable": True, "max_outer_iterations": 3},
        },
    )

    # Confirm we actually exercised the hierarchical (L2) path.
    assert info["anti_degeneracy"]["per_angle_mode"] == "individual"
    assert info["anti_degeneracy"]["hierarchical_active"] is True

    assert np.isfinite(info["ssr"]), f"ssr is not finite: {info['ssr']}"
    assert np.isfinite(info["ssr_frozen_baseline"]), (
        f"ssr_frozen_baseline is not finite: {info['ssr_frozen_baseline']}"
    )
    # Optimizing the per-angle scaling tail cannot worsen the data objective
    # versus the frozen per-angle quantile baseline (shared fitted physics).
    assert info["ssr"] <= info["ssr_frozen_baseline"] + 1e-6, (
        f"ssr={info['ssr']:.6e} > ssr_frozen_baseline={info['ssr_frozen_baseline']:.6e}"
    )


def test_streaming_result_surfaces_anti_degeneracy_block():
    """build_hybrid_streaming_result must propagate info['anti_degeneracy'] into
    the public OptimizationResult.nlsq_diagnostics.

    Regression for the cross-mode parity gap: the streaming fit computes the
    symmetric anti-degeneracy activation block, but the result builder rebuilt
    diagnostics from scratch and dropped it, so L2/L3/L4 always reported
    inactive on the public result. This asserts at the OptimizationResult
    boundary (not just the raw info dict).
    """
    import numpy as np

    from xpcsjax.optimization.nlsq.heterodyne_result_builder import (
        build_hybrid_streaming_result,
    )
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne,
    )

    # Real individual-mode run → L2 hierarchical + L3 active, L4 monitor present.
    model, c2, phi = _make_synthetic_heterodyne(n_phi=4, n_t=6)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()
    popt, pcov, info = fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={
            "warmup_iterations": 5,
            "max_warmup_iterations": 10,
            "gauss_newton_max_iterations": 5,
            "verbose": 0,
        },
        anti_degeneracy_config={
            "per_angle_mode": "individual",
            "hierarchical": {"enable": True, "max_outer_iterations": 3},
        },
    )
    ad = info["anti_degeneracy"]
    assert ad["hierarchical_active"] is True  # sanity: individual ran L2

    result = build_hybrid_streaming_result(
        model=model,
        popt=popt,
        pcov=pcov,
        info=info,
        phi_angles=phi,
    )
    diag = result.nlsq_diagnostics
    # The public result must carry the SAME activation keys as the raw info.
    assert diag["hierarchical_active"] == ad["hierarchical_active"] is True
    assert diag["regularization_active"] == ad["regularization_active"]
    assert "gradient_monitor" in diag  # L4 ran -> surfaced
    assert diag["per_angle_mode"] == "individual"  # real mode, not "hybrid_streaming"


def test_streaming_result_without_anti_degeneracy_defaults_inactive():
    """Backward compat: info lacking 'anti_degeneracy' → result reports inactive."""
    import numpy as np

    from xpcsjax.optimization.nlsq.heterodyne_result_builder import (
        build_hybrid_streaming_result,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=3, n_t=6)
    n = model.param_manager.n_varying
    result = build_hybrid_streaming_result(
        model=model,
        popt=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        pcov=np.eye(n),
        info={"nit": 1, "success": True, "n_data_points": 10},
        phi_angles=phi,
    )
    diag = result.nlsq_diagnostics
    assert diag["hierarchical_active"] is False
    assert diag["regularization_active"] is False
    assert "gradient_monitor" not in diag  # absent when L4 didn't run


def test_pointwise_model_rejects_removed_token():
    """The removed reparam tokens (and the legacy alias) are erased:
    build_heterodyne_pointwise_model must raise ValueError for them, and the
    builder no longer accepts the dropped coefficient-order kwarg.

    Token literals are rebuilt from fragments so this module stays clean under
    the Phase-7 token gate.
    """
    import inspect

    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies import heterodyne_hybrid_streaming as hs
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        build_heterodyne_pointwise_model,
    )

    f = "four" + "ier"

    # The coefficient-order kwarg is gone from the signature entirely.
    sig = inspect.signature(build_heterodyne_pointwise_model)
    assert f"{f}_order" not in sig.parameters, (
        f"{f}_order must be removed from build_heterodyne_pointwise_model"
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=6, n_t=8)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    for bad in (f, "in" + "dependent"):
        with pytest.raises(ValueError, match=f"{f}|in.dependent|unknown per_angle_mode"):
            build_heterodyne_pointwise_model(
                stratified_data=strat,
                model=model,
                physical_param_names=list(model.param_manager.varying_names),
                per_angle_mode=bad,
            )

    # No reparam symbol survives at module scope.
    assert not hasattr(hs, f"{f.capitalize()}Reparameterizer")


@pytest.mark.parametrize("mode", ["constant", "averaged", "individual"])
def test_meta_has_no_reparam_keys(mode):
    """After the reparam teardown, meta must carry zero reparam-related keys for
    every resolved mode, and per_angle_mode must be the canonical token.

    Token literals are rebuilt from fragments to keep this module gate-clean.
    """
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        build_heterodyne_pointwise_model,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=4, n_t=8)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    _fn, _x, _y, _p0, meta = build_heterodyne_pointwise_model(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        per_angle_mode=mode,
    )
    f = "four" + "ier"
    forbidden = {f, f"{f}_effective_mode", f"{f}_order", f"{f}_basis_dim"}
    assert forbidden.isdisjoint(meta.keys()), (
        f"meta still carries reparam keys: {forbidden & set(meta.keys())}"
    )
    assert meta["per_angle_mode"] == mode
    assert "n_scaling" in meta and "n_physics_varying" in meta


@pytest.mark.parametrize(
    "token,n_phi,threshold,expected",
    [
        ("auto", 4, 3, "averaged"),
        ("auto", 2, 3, "individual"),
        ("constant", 4, 3, "constant"),
        ("individual", 4, 3, "individual"),
        ("averaged", 2, 3, "averaged"),
    ],
)
def test_streaming_resolves_canonical_mode(monkeypatch, token, n_phi, threshold, expected):
    """fit_with_stratified_hybrid_streaming_heterodyne resolves per_angle_mode via the
    shared resolver to a canonical token, and stamps it on diagnostics."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies import heterodyne_hybrid_streaming as hs

    captured = {}
    real_builder = hs.build_heterodyne_pointwise_model

    def _spy(*, stratified_data, model, physical_param_names, per_angle_mode):
        captured["mode"] = per_angle_mode
        return real_builder(
            stratified_data=stratified_data,
            model=model,
            physical_param_names=physical_param_names,
            per_angle_mode=per_angle_mode,
        )

    monkeypatch.setattr(hs, "build_heterodyne_pointwise_model", _spy)

    model, c2, phi = _make_synthetic_heterodyne(n_phi=n_phi, n_t=8)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()
    _, _, info = hs.fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={
            "warmup_iterations": 5,
            "max_warmup_iterations": 10,
            "gauss_newton_max_iterations": 5,
            "verbose": 0,
        },
        anti_degeneracy_config={"per_angle_mode": token, "constant_scaling_threshold": threshold},
    )
    assert captured["mode"] == expected
    assert info["anti_degeneracy"]["per_angle_mode"] == expected


def test_l2_branch_uses_identity_layout_no_permute():
    """Native heterodyne vector is scaling-first (Phase 4), matching
    HierarchicalOptimizer's [per_angle | physics] convention. The L2 branch must
    pass the vector straight through — no permute/un-permute. Guard: the module no
    longer constructs a non-identity permutation in the L2 branch."""
    import inspect

    from xpcsjax.optimization.nlsq.strategies import heterodyne_hybrid_streaming as hs

    src = inspect.getsource(hs.fit_with_stratified_hybrid_streaming_heterodyne)
    assert "unperm" not in src, "L2 un-permute survived; native vector is already scaling-first"
    assert "[perm]" not in src, (
        "L2 permute survived; retire to identity (Phase 4 made native scaling-first)"
    )


def test_l2_individual_runs_and_beats_frozen_baseline():
    """individual mode drives the L2 hierarchical branch; with the permute retired
    the result still ties-or-beats the frozen-quantile SSR baseline."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne,
    )

    # n_phi=2 -> auto resolves to individual (threshold=3), exercising the L2 branch.
    model, c2, phi = _make_synthetic_heterodyne(n_phi=2, n_t=8)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()
    _, _, info = fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={"verbose": 0},
        anti_degeneracy_config={
            "per_angle_mode": "individual",
            "hierarchical": {"max_outer_iterations": 3},
        },
    )
    assert info["anti_degeneracy"]["hierarchical_active"] is True
    assert info["anti_degeneracy"]["per_angle_mode"] == "individual"
    assert np.isfinite(info["ssr"]) and np.isfinite(info["ssr_frozen_baseline"])
    assert info["ssr"] <= info["ssr_frozen_baseline"] + 1e-9, (
        f"L2 individual ssr={info['ssr']:.6e} > frozen={info['ssr_frozen_baseline']:.6e}"
    )


@pytest.mark.parametrize("mode,n_phi,n_opt", [("averaged", 4, 2), ("individual", 2, 4)])
def test_diagnostics_stamps_canonical_token_and_n_optimized(mode, n_phi, n_opt):
    """The anti_degeneracy block stamps the canonical resolved token, the
    laminar_flow_inactive L5 sentinel, and the new n_optimized key."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=n_phi, n_t=8)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()
    _, _, info = fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={"verbose": 0},
        anti_degeneracy_config={
            "per_angle_mode": mode,
            "hierarchical": {"max_outer_iterations": 2},
        },
    )
    ad = info["anti_degeneracy"]
    assert ad["per_angle_mode"] == mode  # canonical resolved token
    assert ad["shear_weighting"] == "laminar_flow_inactive"
    assert ad["n_optimized"] == n_opt
    for k in ("hierarchical_active", "regularization_active"):
        assert k in ad


def test_streaming_above_threshold_ssr_not_worse_after_unification():
    """Phase-4 gate (averaged default, n_phi>=threshold). A real streaming optimizer
    run on a small synthetic >threshold dataset must produce optimized SSR
    no-worse-than the frozen-quantile baseline, with the canonical 'averaged' token.
    Synthetic + small => always runnable (NOT an availability-gated oracle)."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne,
    )

    # n_phi=4 >= default threshold 3 -> auto resolves to averaged.
    model, c2, phi = _make_synthetic_heterodyne(n_phi=4, n_t=8)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()
    popt, _pcov, info = fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={
            "warmup_iterations": 10,
            "max_warmup_iterations": 20,
            "gauss_newton_max_iterations": 10,
            "verbose": 0,
        },
        anti_degeneracy_config={"per_angle_mode": "auto"},  # default threshold=3
    )
    assert info["anti_degeneracy"]["per_angle_mode"] == "averaged"
    assert np.isfinite(info["ssr"]) and np.isfinite(info["ssr_frozen_baseline"])
    assert np.all(np.isfinite(popt))
    assert info["ssr"] <= info["ssr_frozen_baseline"] + 1e-9, (
        f"unification regressed streaming SSR: ssr={info['ssr']:.6e} > "
        f"frozen={info['ssr_frozen_baseline']:.6e}"
    )


def test_streaming_diagnostics_block_is_symmetric():
    """The streaming anti_degeneracy block exposes the symmetric activation keys
    (replaces the retired in-module token-scan self-test; the external Phase-7
    gate now enforces token absence across the suite)."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=4, n_t=8)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()
    _, _, info = fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={"verbose": 0},
        anti_degeneracy_config={"per_angle_mode": "auto"},
    )
    ad = info["anti_degeneracy"]
    for key in (
        "hierarchical_active",
        "regularization_active",
        "shear_weighting",
        "per_angle_mode",
    ):
        assert key in ad, f"streaming anti_degeneracy block missing {key!r}"


def test_frozen_per_angle_scaling_invariant_to_input_phi_order():
    """Regression (2026-06-18 audit, P1): the frozen per-angle scaling is keyed by
    the SORTED phi_unique, so it must be invariant to the order the input angles
    arrive in. The old ``reindex`` permuted the frozen contrast/offset onto the
    WRONG angles whenever the input phi was not already ascending (identity only
    for pre-sorted phi, the sole case the suite exercised).

    Build the same (phi, c2) pairs in ascending and descending order; after both
    resolve to the same sorted phi_unique, the frozen contrast/offset arrays must
    match element-for-element. Each angle is given a distinct amplitude so a
    permutation would be detectable.
    """
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        build_heterodyne_pointwise_model,
    )

    # n_t large enough that each angle clears the estimator's >=100-point floor
    # ((n_t-1)*(n_t-2) = 15*14 = 210); below it every angle falls back to the
    # SAME midpoint default and the frozen scaling is uniform (can't detect a
    # permutation).
    model, c2, phi = _make_synthetic_heterodyne(n_phi=3, n_t=16)
    # Scale each angle distinctly (downward, to stay within the Siegert ceiling
    # and the contrast/offset bounds) so the quantile estimator returns three
    # distinct contrast/offset values — a mis-permutation then changes them.
    factors = np.array([0.7, 0.85, 1.0])[:, None, None]
    c2_distinct = c2 * factors

    # Descending presentation: reverse BOTH phi and the matching c2 rows so each
    # angle keeps its own data, only the arrival order changes.
    phi_desc = phi[::-1].copy()
    c2_desc = c2_distinct[::-1].copy()

    def _frozen(c2_in, phi_in):
        strat = build_heterodyne_stratified_data(model, c2_in, phi_in, weights=None)
        _fn, _x, _y, _p0, meta = build_heterodyne_pointwise_model(
            stratified_data=strat,
            model=model,
            physical_param_names=list(model.param_manager.varying_names),
        )
        return (
            np.asarray(meta["phi_unique"]),
            np.asarray(meta["contrast_arr"]),
            np.asarray(meta["offset_arr"]),
        )

    phiu_a, contrast_a, offset_a = _frozen(c2_distinct, phi)
    phiu_d, contrast_d, offset_d = _frozen(c2_desc, phi_desc)

    # Both resolve to the same sorted phi grid.
    np.testing.assert_allclose(phiu_a, phiu_d)
    # The per-angle amplitudes are genuinely distinct (so the test could catch a
    # permutation), and the frozen scaling is order-invariant.
    assert np.ptp(contrast_a) > 0, "test setup: per-angle contrasts not distinct"
    np.testing.assert_allclose(contrast_a, contrast_d, rtol=1e-12, atol=1e-12)
    np.testing.assert_allclose(offset_a, offset_d, rtol=1e-12, atol=1e-12)
