"""Tests for heterodyne stratified hybrid-streaming pipeline (Phase 2)."""
from __future__ import annotations

import numpy as np


def _make_synthetic_heterodyne(n_phi: int = 2, n_t: int = 8, seed: int = 0):
    """Build a tiny synthetic heterodyne dataset from the live kernel.

    Returns (model, c2, phi) where c2 has shape (n_phi, n_t, n_t) and
    is generated by the real compute_c2_heterodyne kernel at the model's
    initial parameters, so residual should be ~0 at those parameters.
    """
    import jax.numpy as jnp

    from xpcsjax.config import ConfigManager
    from xpcsjax.core.heterodyne_jax_backend import compute_c2_heterodyne
    from xpcsjax.core.heterodyne_model_stateful import HeterodyneModel

    cfg = ConfigManager("xpcsjax/config/templates/xpcsjax_two_component.yaml")
    model = HeterodyneModel.from_config(cfg.config)

    t = np.arange(1, n_t + 1, dtype=np.float64) * model.dt
    model.sync_time_axis(t)

    phi = np.linspace(-5.0, 5.0, n_phi).astype(np.float64)
    full = jnp.asarray(model.param_manager.get_full_values(), dtype=jnp.float64)
    contrast, offset = model.scaling.get_for_angle(0)

    c2 = np.stack(
        [
            np.asarray(
                compute_c2_heterodyne(full, model.t, model.q, model.dt, float(p), contrast, offset)
            )
            for p in phi
        ]
    )  # shape: (n_phi, n_t, n_t)

    return model, c2, phi

def test_model_fn_pointwise_matches_kernel():
    """model_fn must reproduce the meshgrid c2 per point using the SAME per-angle
    scaling it computed (decoupled from scaling estimation accuracy)."""
    import jax.numpy as jnp

    from xpcsjax.core.heterodyne_jax_backend import compute_c2_heterodyne
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        build_heterodyne_pointwise_model,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=2, n_t=8)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    model_fn, x_data, y_data, p0, meta = build_heterodyne_pointwise_model(
        stratified_data=strat, model=model,
        physical_param_names=list(model.param_manager.varying_names),
    )
    phi_unique = np.asarray(meta["phi_unique"])
    contrast_arr = np.asarray(meta["contrast_arr"])
    offset_arr = np.asarray(meta["offset_arr"])
    full = np.asarray(model.param_manager.get_full_values())

    pred = np.asarray(model_fn(jnp.asarray(x_data), *[jnp.asarray(v) for v in p0]))

    # Expected: per-point meshgrid c2 with the SAME scaling meta reports.
    meshes = [np.asarray(compute_c2_heterodyne(jnp.asarray(full), model.t, model.q, model.dt,
                                               float(phi_unique[a]), float(contrast_arr[a]), float(offset_arr[a])))
              for a in range(len(phi_unique))]
    expected = np.array([meshes[int(x_data[k, 0])][int(x_data[k, 1]), int(x_data[k, 2])]
                         for k in range(x_data.shape[0])])
    assert np.max(np.abs(pred - expected)) < 1e-6, f"max diff {np.max(np.abs(pred - expected)):.3e}"


def test_fit_with_stratified_hybrid_streaming_heterodyne_dispatch(monkeypatch):
    import xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming as hs
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )

    captured = {}

    class _FakeOpt:
        def __init__(self, config):
            captured["config"] = config

        def fit(self, data_source, func, p0, bounds=None, sigma=None, **kw):
            captured["n_params"] = len(p0)
            captured["has_func"] = callable(func)
            n = len(p0)
            return {"x": np.zeros(n), "pcov": np.eye(n), "perr": np.zeros(n), "nit": 5, "success": True}

    monkeypatch.setattr(hs, "AdaptiveHybridStreamingOptimizer", _FakeOpt)

    model, c2, phi = _make_synthetic_heterodyne()
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lower, upper = model.param_manager.get_bounds()
    popt, pcov, info = hs.fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat, model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values()),
        bounds=(np.asarray(lower), np.asarray(upper)),
        hybrid_config={"enable": True, "warmup_iterations": 30, "chunk_size": 4000},
    )
    assert popt.shape[0] == model.param_manager.n_varying
    assert pcov.shape == (popt.shape[0], popt.shape[0])
    assert info["nit"] == 5
    assert captured["config"].warmup_iterations == 30
    assert captured["config"].chunk_size == 4000
    assert captured["has_func"] is True


def test_build_hybrid_streaming_result():
    from xpcsjax.optimization.nlsq.heterodyne_result_builder import build_hybrid_streaming_result

    model, c2, phi = _make_synthetic_heterodyne()
    n = model.param_manager.n_varying
    res = build_hybrid_streaming_result(
        model=model, popt=np.zeros(n), pcov=np.eye(n),
        info={"nit": 4, "success": True, "hybrid_streaming_diagnostics": {"phase": "done"}},
        phi_angles=phi,
    )
    assert hasattr(res, "parameters")
    assert isinstance(res.nlsq_diagnostics, dict)
    assert res.nlsq_diagnostics["hybrid_streaming"]["phase"] == "done"
    assert res.nlsq_diagnostics.get("shear_weighting") == "not_applicable_heterodyne"


# ---------------------------------------------------------------------------
# Phase 2 Task 4: dispatch gate tests
# ---------------------------------------------------------------------------


def _install_model_stub(monkeypatch, model):
    import sys
    import types

    fake_mod = types.ModuleType("xpcsjax.core.heterodyne_model_stateful")

    class _M:
        @classmethod
        def from_config(cls, _cfg):
            return model

    fake_mod.HeterodyneModel = _M
    monkeypatch.setitem(sys.modules, "xpcsjax.core.heterodyne_model_stateful", fake_mod)


class _Cfg:
    def __init__(self, c):
        self.config = c


def test_hybrid_fires_on_streaming_tier(monkeypatch):
    import xpcsjax.optimization.nlsq as nlsq_pkg
    from xpcsjax.optimization.nlsq import heterodyne_memory as hm

    model, c2, phi = _make_synthetic_heterodyne()
    _install_model_stub(monkeypatch, model)

    # Force tier = STREAMING
    class _Dec:
        strategy = hm.NLSQStrategy.STREAMING
        peak_memory_gb = 99.0
        threshold_gb = 1.0

    monkeypatch.setattr(hm, "select_nlsq_strategy", lambda *a, **k: _Dec())

    called = {}
    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming.fit_with_stratified_hybrid_streaming_heterodyne",
        lambda **k: (called.setdefault("yes", True), (__import__("numpy").zeros(model.param_manager.n_varying),
                     __import__("numpy").eye(model.param_manager.n_varying), {"nit": 1, "success": True}))[1],
    )
    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.heterodyne_core.fit_nlsq_multi_phi",
        lambda *a, **k: (_ for _ in ()).throw(AssertionError("joint path must not run when hybrid fires")),
    )

    cfg = _Cfg({"analysis_mode": "two_component",
                "optimization": {"nlsq": {"hybrid_streaming": {"enable": True}}}})
    data = {"c2_exp": c2, "phi_angles_list": phi}
    nlsq_pkg.fit_nlsq(data, cfg)
    assert called.get("yes") is True


def test_hybrid_does_not_fire_on_standard_tier(monkeypatch):
    import xpcsjax.optimization.nlsq as nlsq_pkg
    from xpcsjax.optimization.nlsq import heterodyne_memory as hm

    model, c2, phi = _make_synthetic_heterodyne()
    _install_model_stub(monkeypatch, model)

    class _Dec:
        strategy = hm.NLSQStrategy.STANDARD
        peak_memory_gb = 0.1
        threshold_gb = 1.0

    monkeypatch.setattr(hm, "select_nlsq_strategy", lambda *a, **k: _Dec())

    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming.fit_with_stratified_hybrid_streaming_heterodyne",
        lambda **k: (_ for _ in ()).throw(AssertionError("hybrid must NOT fire on STANDARD tier")),
    )
    joint = {}
    import numpy as _np

    class _R:
        parameters = _np.zeros(1)
        chi_squared = 0.0
        reduced_chi_squared = 0.0
        success = True
        message = "ok"
        nlsq_diagnostics: dict = {}

    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.heterodyne_core.fit_nlsq_multi_phi",
        lambda *a, **k: joint.setdefault("yes", True) or _R(),
    )

    cfg = _Cfg({"analysis_mode": "two_component",
                "optimization": {"nlsq": {"hybrid_streaming": {"enable": True}}}})
    data = {"c2_exp": c2, "phi_angles_list": phi}
    nlsq_pkg.fit_nlsq(data, cfg)
    assert joint.get("yes") is True  # fell through to the normal joint fit


def test_cmaes_precedence_over_hybrid(monkeypatch):
    import xpcsjax.optimization.nlsq as nlsq_pkg
    from xpcsjax.optimization.nlsq import heterodyne_memory as hm

    model, c2, phi = _make_synthetic_heterodyne()
    _install_model_stub(monkeypatch, model)

    class _Dec:
        strategy = hm.NLSQStrategy.STREAMING
        peak_memory_gb = 99.0
        threshold_gb = 1.0

    monkeypatch.setattr(hm, "select_nlsq_strategy", lambda *a, **k: _Dec())

    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming.fit_with_stratified_hybrid_streaming_heterodyne",
        lambda **k: (_ for _ in ()).throw(AssertionError("hybrid must not run when cmaes on")),
    )
    import numpy as _np

    class _R:
        parameters = _np.zeros(1)
        chi_squared = 0.0
        reduced_chi_squared = 0.0
        success = True
        message = "ok"
        nlsq_diagnostics: dict = {}

    joint = {}
    monkeypatch.setattr(
        "xpcsjax.optimization.nlsq.heterodyne_core.fit_nlsq_multi_phi",
        lambda *a, **k: joint.setdefault("yes", True) or _R(),
    )
    cfg = _Cfg({"analysis_mode": "two_component",
                "optimization": {"nlsq": {"cmaes": {"enable": True},
                                          "hybrid_streaming": {"enable": True}}}})
    data = {"c2_exp": c2, "phi_angles_list": phi}
    nlsq_pkg.fit_nlsq(data, cfg)
    assert joint.get("yes") is True


def test_pointwise_data_excludes_t0_and_diagonal():
    """Pointwise training data must match the meshgrid residual support:
    no diagonal, no t=0 row/col -> (n_t-1)*(n_t-2) points per angle."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        build_heterodyne_pointwise_model,
    )
    n_phi, n_t = 2, 8
    model, c2, phi = _make_synthetic_heterodyne(n_phi=n_phi, n_t=n_t)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    _fn, x_data, y_data, _p0, meta = build_heterodyne_pointwise_model(
        stratified_data=strat, model=model,
        physical_param_names=list(model.param_manager.varying_names),
    )
    t1 = x_data[:, 1]
    t2 = x_data[:, 2]
    assert not (t1 == t2).any(), "diagonal not excluded"
    assert (t1 > 0).all() and (t2 > 0).all(), "t=0 boundary not excluded"
    assert x_data.shape[0] == n_phi * (n_t - 1) * (n_t - 2)
    assert y_data.shape[0] == x_data.shape[0]
    assert meta["n_data_points"] == x_data.shape[0]


def test_initial_params_override_is_honored(monkeypatch):
    import xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming as hs
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    seen = {}
    class _FakeOpt:
        def __init__(self, config): pass
        def fit(self, data_source, func, p0, bounds=None, sigma=None, **kw):
            seen["p0"] = np.asarray(p0).copy()
            n = len(p0)
            return {"x": np.zeros(n), "pcov": np.eye(n), "nit": 1, "success": True}
    monkeypatch.setattr(hs, "AdaptiveHybridStreamingOptimizer", _FakeOpt)
    model, c2, phi = _make_synthetic_heterodyne()
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    n = model.param_manager.n_varying
    custom = np.arange(1, n + 1, dtype=np.float64) * 1.5
    hs.fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat, model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=custom, bounds=None, hybrid_config={"enable": True},
    )
    assert np.allclose(seen["p0"], custom), "initial_params override ignored"


def test_reduced_chi_squared_uses_data_dof():
    from xpcsjax.optimization.nlsq.heterodyne_result_builder import build_hybrid_streaming_result
    model, c2, phi = _make_synthetic_heterodyne()
    n = model.param_manager.n_varying
    res = build_hybrid_streaming_result(
        model=model, popt=np.zeros(n), pcov=np.eye(n),
        info={"nit": 1, "success": True, "n_data_points": 100_000,
              "hybrid_streaming_diagnostics": {}},
        phi_angles=phi,
    )
    # dof must reflect n_data - n_params (~100k), not n_params (~14). With chi2 ~ O(n_data),
    # reduced should not be astronomically inflated. Just assert it's finite and the result is built.
    assert np.isfinite(res.reduced_chi_squared) or res.reduced_chi_squared != res.reduced_chi_squared  # finite or NaN ok


def test_pointwise_model_auto_averaged_param_layout():
    """auto_averaged appends 2 optimized scaling params; model_fn reads them."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        build_heterodyne_pointwise_model,
    )

    # _make_synthetic_heterodyne returns (model, c2, phi)
    model, c2, phi = _make_synthetic_heterodyne()
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)

    model_fn, x_data, y_data, p0, meta = build_heterodyne_pointwise_model(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        per_angle_mode="auto_averaged",
    )
    n_phys = len(model.param_manager.get_initial_values())
    assert len(p0) == n_phys + 2
    assert np.isclose(p0[n_phys], float(np.mean(meta["contrast_arr"])))
    assert np.isclose(p0[n_phys + 1], float(np.mean(meta["offset_arr"])))
    pred = np.asarray(model_fn(x_data[:8], *[float(v) for v in p0]))
    assert pred.shape == (8,)
    assert np.all(np.isfinite(pred))
    assert meta["per_angle_mode"] == "auto_averaged"
    assert meta["n_scaling"] == 2
    assert meta["n_physics_varying"] == n_phys
    scaling_lower, scaling_upper = meta["scaling_bounds"]
    assert scaling_lower.dtype == np.float64
    assert scaling_upper.dtype == np.float64
    assert len(scaling_lower) == 2
    assert len(scaling_upper) == 2
    assert scaling_lower[0] == 0.01
    assert np.isclose(scaling_upper[0], max(2.0 * p0[n_phys], 1.0))


def test_streaming_auto_averaged_optimizes_scaling_and_sets_group_variance(monkeypatch):
    """Task 2 (structural): anti_degeneracy_config consumed; auto_averaged resolves;
    group-variance config injected with the correct indices.

    Uses a MOCK optimizer that returns p0 unchanged, so this test asserts ONLY
    the structural / config contract (param layout, mode, spliced bounds, and the
    HybridStreamingConfig group-variance fields). The SSR-improvement claim is
    verified separately by test_streaming_auto_averaged_real_run_ssr_not_worse,
    because with a no-op optimizer popt == p0 and SSR parity is vacuous.
    """
    import xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming as hs
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )

    captured = {}

    class _FakeOpt:
        def __init__(self, config):
            captured["config"] = config

        def fit(self, data_source, func, p0, bounds=None, sigma=None, **kw):
            captured["p0_len"] = len(p0)
            captured["bounds"] = bounds
            n = len(p0)
            # Return p0 unchanged — a no-op (structural-contract) fit
            return {
                "x": np.asarray(p0, dtype=np.float64),
                "pcov": np.eye(n),
                "nit": 3,
                "success": True,
            }

    monkeypatch.setattr(hs, "AdaptiveHybridStreamingOptimizer", _FakeOpt)

    # n_phi=3 — exercises the multi-angle path
    model, c2, phi = _make_synthetic_heterodyne(n_phi=3, n_t=6)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)

    n_phys = model.param_manager.n_varying
    lower_phys, upper_phys = model.param_manager.get_bounds()
    p0_phys = np.asarray(model.param_manager.get_initial_values(), dtype=np.float64)

    popt, pcov, info = hs.fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=p0_phys,
        bounds=(np.asarray(lower_phys, dtype=np.float64), np.asarray(upper_phys, dtype=np.float64)),
        anti_degeneracy_config={"per_angle_mode": "auto"},
    )

    # popt has 2 extra scaling params appended
    assert len(popt) == n_phys + 2, f"Expected {n_phys + 2} params, got {len(popt)}"
    assert info["anti_degeneracy"]["per_angle_mode"] == "auto_averaged"
    # bounds were spliced to include scaling tail
    assert captured["bounds"] is not None
    assert len(captured["bounds"][0]) == n_phys + 2
    assert len(captured["bounds"][1]) == n_phys + 2
    # HybridStreamingConfig must carry the group-variance regularization fields
    cfg = captured["config"]
    assert cfg.enable_group_variance_regularization is True
    assert cfg.group_variance_lambda > 0.0
    base = n_phys
    assert cfg.group_variance_indices == [(base, base + 1), (base + 1, base + 2)]


def test_streaming_auto_small_n_phi_does_not_crash(monkeypatch):
    """Fix 1 regression: sub-threshold `auto` (n_phi=2) must NOT route to the
    unimplemented `individual` mode and raise NotImplementedError. It must route
    to `auto_averaged` (works for any n_phi >= 1)."""
    import xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming as hs
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )

    class _FakeOpt:
        def __init__(self, config):
            pass

        def fit(self, data_source, func, p0, bounds=None, sigma=None, **kw):
            n = len(p0)
            return {"x": np.asarray(p0, dtype=np.float64), "pcov": np.eye(n),
                    "nit": 1, "success": True}

    monkeypatch.setattr(hs, "AdaptiveHybridStreamingOptimizer", _FakeOpt)

    # n_phi=2 — below the old threshold=3, which previously routed to 'individual'
    model, c2, phi = _make_synthetic_heterodyne(n_phi=2, n_t=6)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lower_phys, upper_phys = model.param_manager.get_bounds()

    popt, pcov, info = hs.fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        bounds=(np.asarray(lower_phys, dtype=np.float64), np.asarray(upper_phys, dtype=np.float64)),
        anti_degeneracy_config={"per_angle_mode": "auto"},
    )
    assert info["anti_degeneracy"]["per_angle_mode"] == "auto_averaged"


def test_streaming_auto_averaged_real_run_ssr_not_worse():
    """Fix 3: REAL optimizer run (no mock). Optimizing the averaged scaling tail
    must do at least as well as the frozen-quantile baseline (shared physics).

    Kept tiny (n_phi=2, n_t=8, few iterations) so it runs in a few seconds.
    Uses finite physics bounds — the path heterodyne_core actually takes (nlsq's
    hybrid-streaming optimizer corrupts ±inf bounds to NaN, see Fix 2)."""
    from xpcsjax.optimization.nlsq.heterodyne_stratified_data import (
        build_heterodyne_stratified_data,
    )
    from xpcsjax.optimization.nlsq.strategies.heterodyne_hybrid_streaming import (
        fit_with_stratified_hybrid_streaming_heterodyne,
    )

    model, c2, phi = _make_synthetic_heterodyne(n_phi=2, n_t=8)
    strat = build_heterodyne_stratified_data(model, c2, phi, weights=None)
    lo, hi = model.param_manager.get_bounds()

    popt, pcov, info = fit_with_stratified_hybrid_streaming_heterodyne(
        stratified_data=strat,
        model=model,
        physical_param_names=list(model.param_manager.varying_names),
        initial_params=np.asarray(model.param_manager.get_initial_values(), dtype=np.float64),
        bounds=(np.asarray(lo, dtype=np.float64), np.asarray(hi, dtype=np.float64)),
        hybrid_config={"warmup_iterations": 10, "max_warmup_iterations": 20,
                       "gauss_newton_max_iterations": 10, "verbose": 0},
        anti_degeneracy_config={"per_angle_mode": "auto"},
    )

    assert info["anti_degeneracy"]["per_angle_mode"] == "auto_averaged"
    assert np.isfinite(info["ssr"])
    assert np.isfinite(info["ssr_frozen_baseline"])
    # Optimizing the scaling tail (shared fitted physics) must beat-or-tie the
    # frozen-quantile default.
    assert info["ssr"] <= info["ssr_frozen_baseline"] + 1e-9, (
        f"ssr={info['ssr']:.6e} > ssr_frozen_baseline={info['ssr_frozen_baseline']:.6e}"
    )
