"""Phase 5 characterization gate: xpcsjax fit must match source homodyne at rtol=1e-10.

Baselines were generated by `scripts/generate_homodyne_baselines.py` running in
the SOURCE homodyne venv. This test runs the SAME configs through xpcsjax and
asserts bit-equivalence on every fitted parameter.

These fits are slow (the laminar configuration runs CMA-ES refinement and takes
~6 minutes). The full suite is gated on the environment variable
`XPCSJAX_RUN_CHARACTERIZATION=1` so normal CI runs skip them; the gate must be
exercised manually whenever Phase 1–4 code lands.

Run manually:

    XPCSJAX_RUN_CHARACTERIZATION=1 uv run pytest tests/characterization/ -v
"""
import json
import os
from pathlib import Path

import numpy as np
import pytest


BASELINES_DIR = Path(__file__).parent / "fixtures" / "baselines"

# Map baseline label → original config absolute path (lives outside the repo).
# When fixtures get bundled in v0.2 these become repo-local.
CONFIGS: dict[str, str] = {
    "static_simon": "/home/wei/Documents/Projects/data/Simon/homodyne_static_config.yaml",
    "laminar_c020": "/home/wei/Documents/Projects/data/C020/homodyne_laminar_flow_config.yaml",
}


# Match the baseline label list to the actual files on disk so missing labels
# (e.g., generation script hadn't been run yet) simply collect zero parametrize cases.
def _available_labels() -> list[str]:
    if not BASELINES_DIR.exists():
        return []
    return sorted(
        p.stem for p in BASELINES_DIR.glob("*.json") if p.stem in CONFIGS
    )


GATE_OPT_IN = os.environ.get("XPCSJAX_RUN_CHARACTERIZATION") == "1"


@pytest.mark.skipif(
    not GATE_OPT_IN,
    reason="characterization gate is slow (~6 min total); set XPCSJAX_RUN_CHARACTERIZATION=1 to run",
)
@pytest.mark.parametrize("label", _available_labels())
def test_homodyne_bit_equivalence(label: str):
    """Fit results must match the pinned baseline at rtol=1e-10."""
    config_path = CONFIGS[label]
    baseline_path = BASELINES_DIR / f"{label}.json"

    assert Path(config_path).exists(), f"config missing: {config_path}"
    assert baseline_path.exists(), f"baseline missing for {label}"

    baseline = json.loads(baseline_path.read_text())

    # Import lazily — module-level imports would force JAX initialization on
    # collection even when the test would skip.
    from xpcsjax.data import load_xpcs_data
    from xpcsjax.optimization.nlsq import fit_nlsq

    data = load_xpcs_data(str(config_path))
    result = fit_nlsq(data, str(config_path))

    actual_params = np.asarray(_extract_params(result), dtype=np.float64)
    expected_params = np.asarray(baseline["parameters"], dtype=np.float64)

    assert actual_params.shape == expected_params.shape, (
        f"{label}: parameter count mismatch "
        f"(xpcsjax={actual_params.shape}, baseline={expected_params.shape})"
    )

    np.testing.assert_allclose(
        actual_params, expected_params, rtol=1e-10,
        err_msg=f"{label}: fitted parameters drifted from homodyne baseline",
    )

    if "chi_squared" in baseline:
        np.testing.assert_allclose(
            float(_extract_chi_squared(result)),
            float(baseline["chi_squared"]),
            rtol=1e-10,
            err_msg=f"{label}: chi_squared drifted",
        )

    if "convergence_status" in baseline:
        actual_status = str(_extract_convergence_status(result))
        assert actual_status == baseline["convergence_status"], (
            f"{label}: convergence_status mismatch "
            f"(xpcsjax={actual_status}, baseline={baseline['convergence_status']})"
        )


def _extract_params(result):
    """Coerce a result-like object into a flat parameter array.

    Homodyne result objects expose `parameters` as either a flat array or a
    dict; xpcsjax mirrors the source. Try the obvious accessors, fall back to
    a `params` attribute."""
    if hasattr(result, "parameters"):
        params = result.parameters
        if isinstance(params, dict):
            return list(params.values())
        return params
    if hasattr(result, "params"):
        return result.params
    raise AttributeError(f"cannot extract parameters from {type(result).__name__}")


def _extract_chi_squared(result):
    for attr in ("chi_squared", "chi2", "final_cost"):
        if hasattr(result, attr):
            return getattr(result, attr)
    raise AttributeError(f"cannot extract chi_squared from {type(result).__name__}")


def _extract_convergence_status(result):
    for attr in ("convergence_status", "status", "convergence"):
        if hasattr(result, attr):
            return getattr(result, attr)
    raise AttributeError(f"cannot extract convergence_status from {type(result).__name__}")
