"""Phase 5 characterization gate: xpcsjax fit must match source homodyne at rtol=1e-10.

Baselines were generated by ``scripts/generate_homodyne_baselines.py`` running in
the SOURCE homodyne venv. This test runs the SAME configs through xpcsjax and
asserts bit-equivalence on every fitted parameter.

These fits are slow (the laminar configuration runs CMA-ES refinement and takes
~6 minutes). The full suite is gated on the environment variable
``XPCSJAX_RUN_CHARACTERIZATION=1`` so normal CI runs skip them; the gate must be
exercised manually whenever Phase 1–4 code lands.

Run manually::

    XPCSJAX_RUN_CHARACTERIZATION=1 uv run pytest tests/characterization/ -v

Three states the conftest distinguishes — each with an explicit skip reason so
a green ``make test-smoke`` cannot silently pretend parity:

1. **Gate not opted in** (default CI/dev): tests skip with a clear "set
   ``XPCSJAX_RUN_CHARACTERIZATION=1``" message.
2. **Gate opted in but baselines missing**: an environment guard test fails
   loudly pointing at ``scripts/generate_homodyne_baselines.py`` — the
   parametrize-over-empty-list silent-pass trap is closed by this guard.
3. **Gate opted in but a config path is dead**: per-label assert fails with the
   exact missing path (the absolute paths to homodyne configs live outside the
   repo and rot when datasets move).
"""

import json
import os
from pathlib import Path

import numpy as np
import pytest

BASELINES_DIR = Path(__file__).parent / "fixtures" / "baselines"

# Map baseline label → original config absolute path (lives outside the repo).
# When fixtures get bundled in v0.2 these become repo-local.
CONFIGS: dict[str, str] = {
    "static_simon": "/home/wei/Documents/Projects/data/Simon/homodyne_static_config.yaml",
    "laminar_c020": "/home/wei/Documents/Projects/data/C020/homodyne_laminar_flow_config.yaml",
}


def _available_labels() -> list[str]:
    """Return labels with both a baseline JSON and a registered config path."""
    if not BASELINES_DIR.exists():
        return []
    return sorted(p.stem for p in BASELINES_DIR.glob("*.json") if p.stem in CONFIGS)


GATE_OPT_IN = os.environ.get("XPCSJAX_RUN_CHARACTERIZATION") == "1"
_SKIP_REASON = (
    "Phase 5 characterization gate is slow (~6 min total). "
    "Set XPCSJAX_RUN_CHARACTERIZATION=1 to run. "
    "This is intentionally NOT a silent pass — the env-guard test "
    "`test_baselines_present_when_gate_active` also runs in this module "
    "and will fail loudly if the gate is on but baselines are missing."
)


# ---------------------------------------------------------------------------
# Environment guard — closes the "parametrize over empty list silently passes"
# trap when the gate is opted in but no baseline fixtures are present.
# ---------------------------------------------------------------------------
@pytest.mark.skipif(not GATE_OPT_IN, reason=_SKIP_REASON)
def test_baselines_present_when_gate_active() -> None:
    """When ``XPCSJAX_RUN_CHARACTERIZATION=1`` is set, baselines MUST exist.

    Without this guard, an empty ``BASELINES_DIR`` would cause
    ``@parametrize("label", [])`` to collect zero cases — pytest happily
    reports green, but the parity oracle never actually ran. That's the
    "silent green smoke pretending parity" failure mode the /double-check
    report flagged.
    """
    labels = _available_labels()
    if not labels:
        pytest.fail(
            f"XPCSJAX_RUN_CHARACTERIZATION=1 but no baseline fixtures found in "
            f"{BASELINES_DIR}. Run `make run-example` (which calls "
            f"`scripts/generate_homodyne_baselines.py`) from the SOURCE homodyne "
            f"venv to (re)generate baselines before running this gate."
        )
    # Also guard against the upstream package not being importable — the gate
    # implicitly assumes homodyne is installed so xpcsjax can run the same
    # config; without it, fit_nlsq would diverge from the baseline for reasons
    # unrelated to xpcsjax code. Use find_spec so we don't actually import
    # homodyne here (saves JAX double-init).
    import importlib.util

    if importlib.util.find_spec("homodyne") is None:
        pytest.fail(
            "XPCSJAX_RUN_CHARACTERIZATION=1 but upstream `homodyne` package is "
            "not importable. Install it into the dev env (`uv pip install "
            "homodyne`) — the parity oracle compares against homodyne's own fit, "
            "not just a frozen JSON snapshot."
        )


@pytest.mark.skipif(not GATE_OPT_IN, reason=_SKIP_REASON)
@pytest.mark.parametrize("label", _available_labels())
def test_homodyne_bit_equivalence(label: str) -> None:
    """Fit results must match the pinned baseline at rtol=1e-10."""
    config_path = CONFIGS[label]
    baseline_path = BASELINES_DIR / f"{label}.json"

    assert Path(config_path).exists(), (
        f"{label}: registered config path is dead — {config_path} not found. "
        f"Update CONFIGS in this file or restore the dataset."
    )
    assert baseline_path.exists(), (
        f"{label}: baseline missing at {baseline_path}. "
        f"Regenerate via `make run-example` (from source homodyne venv)."
    )

    baseline = json.loads(baseline_path.read_text())

    # Import lazily — module-level imports would force JAX initialization on
    # collection even when the test would skip.
    from xpcsjax.data import load_xpcs_data
    from xpcsjax.optimization.nlsq import fit_nlsq

    data = load_xpcs_data(str(config_path))
    result = fit_nlsq(data, str(config_path))

    actual_params = np.asarray(_extract_params(result), dtype=np.float64)
    expected_params = np.asarray(baseline["parameters"], dtype=np.float64)

    assert actual_params.shape == expected_params.shape, (
        f"{label}: parameter count mismatch "
        f"(xpcsjax={actual_params.shape}, baseline={expected_params.shape})"
    )

    np.testing.assert_allclose(
        actual_params,
        expected_params,
        rtol=1e-10,
        err_msg=f"{label}: fitted parameters drifted from homodyne baseline",
    )

    if "chi_squared" in baseline:
        np.testing.assert_allclose(
            float(_extract_chi_squared(result)),
            float(baseline["chi_squared"]),
            rtol=1e-10,
            err_msg=f"{label}: chi_squared drifted",
        )

    if "convergence_status" in baseline:
        actual_status = str(_extract_convergence_status(result))
        assert actual_status == baseline["convergence_status"], (
            f"{label}: convergence_status mismatch "
            f"(xpcsjax={actual_status}, baseline={baseline['convergence_status']})"
        )


def _extract_params(result):
    """Coerce a result-like object into a flat parameter array.

    Homodyne result objects expose ``parameters`` as either a flat array or a
    dict; xpcsjax mirrors the source. Try the obvious accessors, fall back to
    a ``params`` attribute."""
    if hasattr(result, "parameters"):
        params = result.parameters
        if isinstance(params, dict):
            return list(params.values())
        return params
    if hasattr(result, "params"):
        return result.params
    raise AttributeError(f"cannot extract parameters from {type(result).__name__}")


def _extract_chi_squared(result):
    for attr in ("chi_squared", "chi2", "final_cost"):
        if hasattr(result, attr):
            return getattr(result, attr)
    raise AttributeError(f"cannot extract chi_squared from {type(result).__name__}")


def _extract_convergence_status(result):
    for attr in ("convergence_status", "status", "convergence"):
        if hasattr(result, attr):
            return getattr(result, attr)
    raise AttributeError(f"cannot extract convergence_status from {type(result).__name__}")
