"""Heterodyne residual-layout parity gate (corpus-loading, not generating).

Asserts xpcsjax's ``compute_multi_angle_residuals`` reproduces the upstream
``heterodyne`` package's residual vector element-for-element on a frozen
synthetic two_component input. The baseline JSON is generated by
``scripts/generate_heterodyne_baselines.py`` (run by the maintainer with
upstream installed); this test imports only stdlib + numpy + xpcsjax.

This is the oracle that pins the t=0-boundary-mask convention: upstream
excludes the t=0 row/column AND the diagonal — shape ``(N-1)*(N-2)`` per
angle — whereas xpcsjax historically excluded only the diagonal — shape
``N*(N-1)`` — silently fitting interpolated t=0 boundary values that upstream
drops.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np

FIXTURE = (
    Path(__file__).resolve().parent
    / "fixtures"
    / "baselines"
    / "heterodyne_residuals.json"
)


def _build_inputs(spec: dict[str, Any]) -> dict[str, np.ndarray]:
    """Reconstruct the deterministic inputs — must match the generator exactly."""
    n, n_phi = spec["N"], spec["n_phi"]
    rng = np.random.default_rng(spec["seed"])
    return {
        "t": np.linspace(0.0, spec["t_max"], n, dtype=np.float64),
        "phi": np.asarray(spec["phi_angles"], dtype=np.float64),
        "params": np.asarray(spec["params"], dtype=np.float64),
        "c2": rng.uniform(1.0, 1.5, size=(n_phi, n, n)).astype(np.float64),
        "weights": np.ones((n_phi, n, n), dtype=np.float64),
        "contrasts": np.asarray(spec["contrasts"], dtype=np.float64),
        "offsets": np.asarray(spec["offsets"], dtype=np.float64),
    }


def test_xpcsjax_matches_upstream_residual_layout() -> None:
    import jax.numpy as jnp

    from xpcsjax.core.heterodyne_jax_backend import compute_multi_angle_residuals

    fixture = json.loads(FIXTURE.read_text())
    spec = fixture["spec"]
    inp = _build_inputs(spec)

    xj = np.asarray(
        compute_multi_angle_residuals(
            jnp.asarray(inp["params"]),
            jnp.asarray(inp["t"]),
            spec["q"],
            spec["dt"],
            jnp.asarray(inp["phi"]),
            jnp.asarray(inp["c2"]),
            jnp.asarray(inp["weights"]),
            jnp.asarray(inp["contrasts"]),
            jnp.asarray(inp["offsets"]),
        )
    )
    upstream = np.asarray(fixture["upstream_residuals"], dtype=np.float64)

    # Layout parity: t=0 boundary row/col excluded -> (N-1)*(N-2) per angle.
    n, n_phi = spec["N"], spec["n_phi"]
    assert xj.size == n_phi * (n - 1) * (n - 2), (
        f"xpcsjax residual size {xj.size} != upstream layout "
        f"n_phi*(N-1)*(N-2) = {n_phi * (n - 1) * (n - 2)}"
    )
    assert xj.shape == upstream.shape

    # Value parity, element-for-element (same cells, same order).
    np.testing.assert_allclose(xj, upstream, rtol=1e-10, atol=1e-12)
