{% set name = "evosax" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/evosax-{{ version }}.tar.gz
  sha256: 38609f64704b48921b500b2d4729779beacd82eb39749978fe8e6db790a790dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=77
    - wheel
  run:
    - python >=3.10
    - numpy >=1.25
    - jax >=0.5.0
    - flax >=0.10.0
    - dotmap
    - matplotlib-base

test:
  imports:
    - evosax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/RobertTLange/evosax
  summary: Evolution Strategies in JAX
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - imewei
