"""Task 30: end-to-end heterodyne smoke fit on synthetic two-component data.

Exercises the full dispatch chain ``fit_nlsq → _fit_nlsq_heterodyne →
fit_nlsq_multi_phi`` against synthetic c2 generated by ``HeterodyneModel``
itself with known parameters. Lives alongside the slow real-data parity test
(``test_two_component_real_data.py``) but runs in seconds — no external
fixtures required, no env-gate.

This is intentionally a *smoke* test: it asserts the pipeline terminates with
a converged result on every phi angle and that the fitted parameters stay
within a loose envelope of the truth. The tight golden-value comparison is
covered by the C044 real-data test in Phase 7.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import yaml

# Tiny time window — keeps the fit under a few seconds while still exercising
# the multi-phi joint solve.
_N_TIMES = 40
_DT = 1.0
_Q = 0.0054
_PHI_ANGLES = np.array([0.0, 45.0], dtype=np.float64)
_NOISE_SIGMA = 1e-3


def _smoke_config_dict() -> dict:
    """Self-contained heterodyne config sufficient for HeterodyneModel.from_config.

    Uses registry defaults for all 14 physics parameters; only the analyzer /
    optimizer sections are populated. The ``parameters`` block is intentionally
    empty so :meth:`ParameterSpace.from_config` falls back to defaults — this
    keeps the test independent of registry-default drift.
    """
    return {
        "analysis_mode": "two_component",
        "analyzer_parameters": {
            "dt": _DT,
            "start_frame": 1,
            "end_frame": _N_TIMES,
            "scattering": {"wavevector_q": _Q},
        },
        "scaling": {
            "n_angles": len(_PHI_ANGLES),
            "mode": "constant",
            "initial_contrast": 0.3,
            "initial_offset": 1.0,
        },
        "optimization": {
            "nlsq": {
                "analysis_mode": "two_component",
                "max_iterations": 50,
                "enable_cmaes": False,
            },
        },
    }


def _write_config(tmp_path: Path) -> Path:
    cfg_path = tmp_path / "smoke.yaml"
    cfg_path.write_text(yaml.safe_dump(_smoke_config_dict()))
    return cfg_path


def _build_synthetic_c2(model) -> np.ndarray:
    """Forward-evaluate the model at each phi to build the c2 stack."""
    rng = np.random.default_rng(seed=20260519)
    c2_stack = np.empty((len(_PHI_ANGLES), _N_TIMES, _N_TIMES), dtype=np.float64)
    for i, phi in enumerate(_PHI_ANGLES):
        c2 = np.asarray(model.compute_correlation(phi_angle=float(phi), angle_idx=i))
        # Small noise so the optimizer has to actually move from the initial
        # point rather than short-circuiting on a zero residual.
        c2_stack[i] = c2 + rng.normal(0.0, _NOISE_SIGMA, size=c2.shape)
    return c2_stack


def test_heterodyne_smoke_fit_recovers_truth(tmp_path):
    """End-to-end heterodyne fit on synthetic data must converge and recover
    parameters within a loose envelope of the truth.

    This is the architectural sibling of the homodyne characterization gate:
    it pins the dispatch chain (``fit_nlsq`` → heterodyne branch →
    ``fit_nlsq_multi_phi``) so a regression in any of those layers is caught
    in CI without needing the C044 cache file or the long real-data fit.
    """
    from xpcsjax.config import ConfigManager
    from xpcsjax.core.heterodyne_model_stateful import HeterodyneModel
    from xpcsjax.optimization.nlsq import fit_nlsq
    from xpcsjax.optimization.nlsq.heterodyne_results import NLSQResult

    cfg_path = _write_config(tmp_path)
    cfg = ConfigManager(str(cfg_path))

    # Truth model: defaults from the registry, accessed via the same config
    # that the fit will use. Recording the truth vector now (before the fit
    # mutates anything) lets us assert recovery downstream.
    truth_model = HeterodyneModel.from_config(cfg.config)
    truth_params = np.asarray(truth_model.get_params(), dtype=np.float64)
    truth_names = list(truth_model.param_names)

    c2 = _build_synthetic_c2(truth_model)
    data = {"c2": c2, "phi": _PHI_ANGLES}

    results = fit_nlsq(data, cfg)

    # ---- Pipeline contract ----------------------------------------------
    assert isinstance(results, list), f"expected list[NLSQResult], got {type(results)}"
    assert len(results) == len(_PHI_ANGLES), (
        f"expected {len(_PHI_ANGLES)} per-angle results, got {len(results)}"
    )
    for r in results:
        assert isinstance(r, NLSQResult)
        params = np.asarray(r.parameters, dtype=np.float64)
        assert np.all(np.isfinite(params)), f"NaN/Inf in fitted parameters: {params}"

    # ---- Recovery envelope ----------------------------------------------
    # Heterodyne's 14-parameter model has well-documented internal degeneracies
    # (see real-data test for the f0/f1/f2 invariant). For the smoke gate we
    # only assert the well-conditioned parameters land near the truth. The
    # tight golden-value check belongs in Phase 7's real-data test, not here.
    first = results[0]
    first_names = list(first.parameter_names)
    first_params = np.asarray(first.parameters, dtype=np.float64)
    name_to_idx = {n: i for i, n in enumerate(first_names)}

    tight_params = ["D0_ref", "alpha_ref", "D0_sample", "alpha_sample"]
    for p in tight_params:
        if p not in name_to_idx:
            pytest.fail(f"smoke fit lost parameter {p!r}; have {first_names}")
        recovered = first_params[name_to_idx[p]]
        truth = truth_params[truth_names.index(p)]
        # Loose envelope: 50% on absolute scale OR rtol=0.5 — whichever wider.
        # We are testing pipeline integrity, not solver quality.
        assert np.isclose(recovered, truth, rtol=0.5, atol=abs(truth) * 0.5 + 1e-6), (
            f"smoke fit drifted on {p}: truth={truth:.4g} recovered={recovered:.4g}"
        )
