"""Task 30: end-to-end heterodyne smoke fit on synthetic two-component data.

Exercises the full dispatch chain ``fit_nlsq → _fit_nlsq_heterodyne →
fit_nlsq_multi_phi`` against synthetic c2 generated by ``HeterodyneModel``
itself with known parameters. Lives alongside the slow real-data parity test
(``test_two_component_real_data.py``) but runs in seconds — no external
fixtures required, no env-gate.

This is intentionally a *smoke* test: it asserts the pipeline terminates with
a converged result on every phi angle and that the fitted parameters stay
within a loose envelope of the truth. The tight golden-value comparison is
covered by the C044 real-data test in Phase 7.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import yaml

# Tiny time window — keeps the fit under a few seconds while still exercising
# the multi-phi joint solve.
_N_TIMES = 40
_DT = 1.0
_Q = 0.0054
# 3 angles so the default per_angle_mode="auto" resolves to "averaged" (the
# joint, well-conditioned path that real 3-angle runs hit). With <3 angles the
# unified auto rule would route to "individual" (sequential single-angle fits),
# which is less constrained for a tiny smoke budget.
_PHI_ANGLES = np.array([0.0, 45.0, 90.0], dtype=np.float64)
_NOISE_SIGMA = 1e-3


def _smoke_config_dict() -> dict:
    """Self-contained heterodyne config sufficient for HeterodyneModel.from_config.

    Uses registry defaults for all 14 physics parameters; only the analyzer /
    optimizer sections are populated. The ``parameters`` block is intentionally
    empty so :meth:`ParameterSpace.from_config` falls back to defaults — this
    keeps the test independent of registry-default drift.
    """
    return {
        "analysis_mode": "two_component",
        "analyzer_parameters": {
            "dt": _DT,
            "start_frame": 1,
            "end_frame": _N_TIMES,
            "scattering": {"wavevector_q": _Q},
        },
        "scaling": {
            "n_angles": len(_PHI_ANGLES),
            "mode": "constant",
            "initial_contrast": 0.3,
            "initial_offset": 1.0,
        },
        "optimization": {
            "nlsq": {
                "analysis_mode": "two_component",
                "max_iterations": 50,
                "enable_cmaes": False,
            },
        },
    }


def _write_config(tmp_path: Path) -> Path:
    cfg_path = tmp_path / "smoke.yaml"
    cfg_path.write_text(yaml.safe_dump(_smoke_config_dict()))
    return cfg_path


def _build_synthetic_c2(model) -> np.ndarray:
    """Forward-evaluate the model at each phi to build the c2 stack."""
    rng = np.random.default_rng(seed=20260519)
    c2_stack = np.empty((len(_PHI_ANGLES), _N_TIMES, _N_TIMES), dtype=np.float64)
    for i, phi in enumerate(_PHI_ANGLES):
        c2 = np.asarray(model.compute_correlation(phi_angle=float(phi), angle_idx=i))
        # Small noise so the optimizer has to actually move from the initial
        # point rather than short-circuiting on a zero residual.
        c2_stack[i] = c2 + rng.normal(0.0, _NOISE_SIGMA, size=c2.shape)
    return c2_stack


def test_heterodyne_smoke_fit_recovers_truth(tmp_path):
    """End-to-end heterodyne fit on synthetic data must converge and recover
    parameters within a loose envelope of the truth.

    This is the architectural sibling of the homodyne characterization gate:
    it pins the dispatch chain (``fit_nlsq`` → heterodyne branch →
    ``fit_nlsq_multi_phi``) so a regression in any of those layers is caught
    in CI without needing the C044 cache file or the long real-data fit.
    """
    from xpcsjax.config import ConfigManager
    from xpcsjax.core.heterodyne_model_stateful import HeterodyneModel
    from xpcsjax.optimization.nlsq import fit_nlsq
    from xpcsjax.optimization.nlsq.results import OptimizationResult

    cfg_path = _write_config(tmp_path)
    cfg = ConfigManager(str(cfg_path))

    # Truth model: defaults from the registry, accessed via the same config
    # that the fit will use. Recording the truth vector now (before the fit
    # mutates anything) lets us assert recovery downstream.
    truth_model = HeterodyneModel.from_config(cfg.config)
    truth_params = np.asarray(truth_model.get_params(), dtype=np.float64)
    truth_names = list(truth_model.param_names)

    c2 = _build_synthetic_c2(truth_model)
    data = {"c2": c2, "phi": _PHI_ANGLES}

    results = fit_nlsq(data, cfg)

    # ---- Pipeline contract ----------------------------------------------
    # After Phase-6 C2-C6 + C5b, ``fit_nlsq_multi_phi`` returns a single
    # :class:`OptimizationResult` for every dispatch mode (constant /
    # averaged / fourier / CMA-ES / individual). ``parameter_names`` for
    # the physics block lives in ``nlsq_diagnostics``; per-angle chi^2
    # lives there too (SSR conservation locked in by B2/C2/C3).
    assert isinstance(results, OptimizationResult), (
        f"expected OptimizationResult, got {type(results)}"
    )
    diag = results.nlsq_diagnostics or {}
    assert "parameter_names" in diag, (
        "OptimizationResult.nlsq_diagnostics must carry parameter_names for joint heterodyne fits"
    )
    assert "chi2_per_angle" in diag, (
        "OptimizationResult must carry chi2_per_angle in nlsq_diagnostics"
    )
    assert np.asarray(diag["chi2_per_angle"]).shape == (len(_PHI_ANGLES),), (
        f"chi2_per_angle shape mismatch: "
        f"{np.asarray(diag['chi2_per_angle']).shape} "
        f"vs expected ({len(_PHI_ANGLES)},)"
    )
    # The optimizer parameter vector for constant mode is just the
    # physics-varying block (per-angle scaling is frozen / fixed). Slice
    # to ``len(parameter_names)`` so we don't accidentally pick up any
    # mode-specific tail (Fourier coefficients in fourier mode, etc.).
    first_names = list(diag["parameter_names"])
    first_params = np.asarray(results.parameters, dtype=np.float64)[: len(first_names)]
    assert np.all(np.isfinite(first_params)), f"NaN/Inf in fitted parameters: {first_params}"

    # ---- Recovery envelope ----------------------------------------------
    # Heterodyne's 14-parameter model has well-documented internal degeneracies
    # (see real-data test for the f0/f1/f2 invariant). For the smoke gate we
    # only assert the well-conditioned parameters land near the truth. The
    # tight golden-value check belongs in Phase 7's real-data test, not here.
    name_to_idx = {n: i for i, n in enumerate(first_names)}

    # ``D0_ref`` is intentionally excluded: with the registry-default truth
    # value of ``alpha_ref ≈ 0`` the time-power-law ``t^alpha_ref ≈ 1``, so
    # ``J_r(t) = D0_ref * t^alpha_ref + D_offset_ref`` collapses to
    # ``D0_ref + D_offset_ref`` — a perfectly degenerate offset trade-off.
    # The real-data parity test (``test_two_component_real_data``) catches
    # ``D0_ref`` drift on the C044 fit where ``alpha_ref`` is well away from
    # zero and the parameter is identifiable. Same reason ``D_offset_ref``
    # is not in this list either.
    tight_params = ["alpha_ref", "D0_sample", "alpha_sample"]
    for p in tight_params:
        if p not in name_to_idx:
            pytest.fail(f"smoke fit lost parameter {p!r}; have {first_names}")
        recovered = first_params[name_to_idx[p]]
        truth = truth_params[truth_names.index(p)]
        # Loose envelope: rtol=0.5 OR atol=0.1 — whichever wider. The atol
        # floor matters because several truth defaults are near zero
        # (e.g. ``alpha_ref ≈ 0``) which would otherwise collapse
        # ``rtol * abs(truth)`` to zero and make the assertion sub-1e-6
        # strict. We are testing pipeline integrity, not solver quality.
        tol = max(abs(truth) * 0.5, 0.1)
        assert np.isclose(recovered, truth, rtol=0.5, atol=tol), (
            f"smoke fit drifted on {p}: truth={truth:.4g} recovered={recovered:.4g}"
        )
